import { Hono } from "hono";
import { readJsonFile, safeId } from "../lib/storage";
import { getAccountForRequest, getPlanTier, isActivePro, usageKey } from "../lib/auth-helpers";
import { FREE_MAIA_DAILY_LIMIT, PRO_MAIA_DAILY_LIMIT, usageDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for account

const app = new Hono();


app.get("/api/account/status", async (c) => {
  const resolved = await getAccountForRequest(c);
  if (resolved instanceof Response) return resolved;
  const { user, account } = resolved;
  const day = usageKey();
  const usage = await readJsonFile<Record<string, number>>(path.join(usageDir, `${safeId(user.id)}-${day}.json`), {});
  return c.json({
    user,
    account: {
      plan: account.plan,
      subscriptionStatus: account.subscriptionStatus || null,
      currentPeriodEnd: account.currentPeriodEnd || null,
      isPro: isActivePro(account),
      trialStart: account.trialStart || null,
      trialEnd: account.trialEnd || null,
      tier: getPlanTier(account),
    },
    usage: {
      day,
      messages: Number(usage.messages || 0),
      freeLimit: FREE_MAIA_DAILY_LIMIT,
      proLimit: PRO_MAIA_DAILY_LIMIT,
    },
  });
});

// ── File Library ─────────────────────────────────────────────────────────────


export default app;
