import { Hono } from "hono";
import { ensureDir, readJsonFile, safeId, writeJsonFile } from "../lib/storage";
import { getCurrentUser, isPlatformAdmin, usageKey } from "../lib/auth-helpers";
import { DATA_ROOT, generatedToolsDir, nclexDir, reportsDir, usageDir, usersDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for admin

const app = new Hono();


app.get("/api/admin/dashboard", async (c) => {
  const user = getCurrentUser(c);
  if (!isPlatformAdmin(user)) return c.json({ error: "Admin access required" }, 403);
  const [users, reports, tools] = await Promise.all([
    listJsonFiles<StoredUser>(usersDir),
    listJsonFiles<any>(reportsDir),
    listJsonFiles<any>(generatedToolsDir),
  ]);
  await ensureDir(usageDir);
  await ensureDir(nclexDir);
  const usageFiles = (await readdir(usageDir).catch(() => [])).filter((file) => file.endsWith(".json"));
  const usageRows = await Promise.all(usageFiles.map(async (file) => {
    const raw = await readJsonFile<Record<string, number>>(path.join(usageDir, file), {});
    const match = file.match(/^(.+)-(\d{4}-\d{2}-\d{2})\.json$/);
    const userId = match?.[1] || file.replace(/\.json$/, "");
    const date = match?.[2] || "unknown";
    const account = users.find((u) => safeId(u.id) === userId || u.id === userId);
    const messages = Number(raw.messages || 0);
    return { file, userId, date, email: account?.email || null, messages, estimatedCost: estimateGeminiCostFromActions(messages) };
  }));
  const nclexFiles = (await readdir(nclexDir).catch(() => [])).filter((file) => file.endsWith(".json"));
  const nclexRows = await Promise.all(nclexFiles.map(async (file) => {
    const attempts = await readJsonFile<any[]>(path.join(nclexDir, file), []);
    const userId = file.replace(/\.json$/, "");
    const account = users.find((u) => safeId(u.id) === userId || u.id === userId);
    const total = attempts.length;
    const right = attempts.filter((a) => a.correct).length;
    return { userId, email: account?.email || null, total, right, percent: total ? Math.round((right / total) * 100) : 0 };
  }));
  const today = usageKey();
  const totalActions = usageRows.reduce((sum, row) => sum + row.messages, 0);
  const todayActions = usageRows.filter((row) => row.date === today).reduce((sum, row) => sum + row.messages, 0);
  const proUsers = users.filter((u) => u.plan === "pro").length;
  const proPlusUsers = users.filter((u) => u.plan === "pro_plus").length;
  const maxUsers = users.filter((u) => u.plan === "max").length;
  return c.json({
    summary: {
      users: users.length,
      proUsers,
      proPlusUsers,
      maxUsers,
      freeUsers: users.length - proUsers - proPlusUsers - maxUsers,
      generatedTools: tools.length,
      pendingTools: tools.filter((t: any) => t.status === "pending").length,
      openReports: reports.filter((r: any) => (r.status || "open") === "open").length,
      totalAiActions: totalActions,
      todayAiActions: todayActions,
      estimatedTotalCost: estimateGeminiCostFromActions(totalActions),
      estimatedTodayCost: estimateGeminiCostFromActions(todayActions),
    },
    users: users.sort((a, b) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))),
    usage: usageRows.sort((a, b) => `${b.date}${b.messages}`.localeCompare(`${a.date}${a.messages}`)),
    generatedTools: tools.sort((a: any, b: any) => String(b.updatedAt || b.createdAt || "").localeCompare(String(a.updatedAt || a.createdAt || ""))),
    reports: reports.sort((a: any, b: any) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))),
    nclex: nclexRows.sort((a, b) => b.total - a.total),
    costAssumptions: { estimatedCostPerAiAction: 0.015, note: "Conservative planning estimate until provider billing exports are connected." },
  });
});

app.post("/api/admin/users/:id", async (c) => {
  const user = getCurrentUser(c);
  if (!isPlatformAdmin(user)) return c.json({ error: "Admin access required" }, 403);
  const id = c.req.param("id");
  const body = await c.req.json().catch(() => ({}));
  const account = await readJsonFile<StoredUser | null>(userPath(id), null);
  if (!account) return c.json({ error: "User not found" }, 404);
  const updated: StoredUser = {
    ...account,
    plan: ["pro", "pro_plus", "max"].includes(body.plan) ? body.plan : "free",
    subscriptionStatus: body.subscriptionStatus === "active" ? "active" : ["pro", "pro_plus", "max"].includes(body.plan) ? "active" : null,
    updatedAt: new Date().toISOString(),
  };
  await writeJsonFile(userPath(id), updated);
  return c.json({ user: updated });
});

app.delete("/api/admin/generated-tools/:id", async (c) => {
  const user = getCurrentUser(c);
  if (!isPlatformAdmin(user)) return c.json({ error: "Admin access required" }, 403);
  const id = slugifyTool(c.req.param("id"));
  const filePath = path.join(generatedToolsDir, `${id}.json`);
  const tool = await readJsonFile<any | null>(filePath, null);
  if (!tool) return c.json({ error: "Tool not found" }, 404);
  const trashDir = path.join(DATA_ROOT, "deleted-generated-tools");
  await ensureDir(trashDir);
  await writeJsonFile(path.join(trashDir, `${id}-${Date.now()}.json`), { ...tool, deletedBy: user.email, deletedAt: new Date().toISOString() });
  await Bun.file(filePath).delete().catch(() => {});
  return c.json({ ok: true });
});

app.post("/api/admin/reports/:id", async (c) => {
  const user = getCurrentUser(c);
  if (!isPlatformAdmin(user)) return c.json({ error: "Admin access required" }, 403);
  const id = String(c.req.param("id") || "").replace(/[^a-zA-Z0-9_-]/g, "");
  const body = await c.req.json().catch(() => ({}));
  const filePath = path.join(reportsDir, `${id}.json`);
  const report = await readJsonFile<any | null>(filePath, null);
  if (!report) return c.json({ error: "Report not found" }, 404);
  const updated = { ...report, status: body.status === "closed" ? "closed" : "open", reviewedBy: user.email, reviewedAt: new Date().toISOString() };
  await writeJsonFile(filePath, updated);
  return c.json({ report: updated });
});

app.get("/api/admin/review", async (c) => {
  const user = getCurrentUser(c);
  if (!isPlatformAdmin(user)) return c.json({ error: "Admin access required" }, 403);
  await ensureGeneratedToolsDir();
  await ensureDir(reportsDir);
  const toolFiles = (await readdir(generatedToolsDir).catch(() => [])).filter((file) => file.endsWith(".json"));
  const tools = (await Promise.all(toolFiles.map(async (file) => readJsonFile<any | null>(path.join(generatedToolsDir, file), null)))).filter(Boolean);
  const reportFiles = (await readdir(reportsDir).catch(() => [])).filter((file) => file.endsWith(".json"));
  const reports = (await Promise.all(reportFiles.map(async (file) => readJsonFile<any | null>(path.join(reportsDir, file), null)))).filter(Boolean);
  return c.json({
    tools: tools.sort((a: any, b: any) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))),
    reports: reports.sort((a: any, b: any) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))),
  });
});

app.post("/api/admin/generated-tools/:id/review", async (c) => {
  const user = getCurrentUser(c);
  if (!isPlatformAdmin(user)) return c.json({ error: "Admin access required" }, 403);
  const id = slugifyTool(c.req.param("id"));
  const body = await c.req.json().catch(() => ({}));
  const filePath = path.join(generatedToolsDir, `${id}.json`);
  const tool = await readJsonFile<any | null>(filePath, null);
  if (!tool) return c.json({ error: "Tool not found" }, 404);
  const status = body.status === "rejected" ? "rejected" : "approved";
  const updated = { ...tool, status, reviewedBy: user.email, reviewedAt: new Date().toISOString() };
  await writeJsonFile(filePath, updated);
  return c.json({ tool: updated });
});


app.get("/api/conversations", async (c) => {


export default app;
