import { Hono } from "hono";
import { ensureDir, readJsonFile, writeJsonFile } from "../lib/storage";
import { getAccountForRequest } from "../lib/auth-helpers";
import { PRICE_TO_PLAN, PRO_MONTHLY_AMOUNT, PRO_YEARLY_AMOUNT, billingDir, usersDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for billing

const app = new Hono();


async function stripeRequest(pathname: string, init: RequestInit = {}) {
  const secret = await readEnv("STRIPE_SECRET_KEY");
  if (!secret) throw new Error("Stripe secret key is not configured");
  const body = init.body as any;
  const headers: Record<string, string> = {
    "Authorization": `Bearer ${secret}`,
    "Content-Type": "application/x-www-form-urlencoded",
    ...(init.headers as Record<string, string> || {}),
  };
  return fetch(`https://api.stripe.com/v1${pathname}`, { ...init, headers, body });
}

async function ensureStripeProductAndPrice(kind: "monthly" | "yearly") {
  const cachePath = path.join(billingDir, `stripe-${kind}.json`);
  const cached = await readJsonFile<any | null>(cachePath, null);
  const amount = kind === "monthly" ? PRO_MONTHLY_AMOUNT : PRO_YEARLY_AMOUNT;
  const interval = kind === "monthly" ? "month" : "year";
  if (cached?.priceId && cached.amount === amount && cached.interval === interval) return cached.priceId as string;
  await ensureDir(billingDir);
  const productRes = await stripeRequest("/products", {
    method: "POST",
    body: new URLSearchParams({
      name: "Bio-Sync Academy Pro MAIA",
      description: "Pro access to MAIA, NCLEX generation, clinical tools, and AI-generated study tools.",
    }),
  });
  if (!productRes.ok) throw new Error(`Stripe product failed: ${productRes.status}`);
  const product = await productRes.json() as any;
  const priceRes = await stripeRequest("/prices", {
    method: "POST",
    body: new URLSearchParams({
      product: product.id,
      currency: "usd",
      unit_amount: String(amount),
      "recurring[interval]": interval,
    }),
  });
  if (!priceRes.ok) throw new Error(`Stripe price failed: ${priceRes.status}`);
  const price = await priceRes.json() as any;
  await writeJsonFile(cachePath, { productId: product.id, priceId: price.id, amount, interval, createdAt: new Date().toISOString() });
  return price.id as string;
}

async function findUserByStripeCustomer(customerId: string): Promise<StoredUser | null> {
  await ensureDir(usersDir);
  const files = (await readdir(usersDir).catch(() => [])).filter((file) => file.endsWith(".json"));
  for (const file of files) {
    const user = await readJsonFile<StoredUser | null>(path.join(usersDir, file), null);
    if (user?.stripeCustomerId === customerId) return user;
  }
  return null;
}

async function updateUserSubscriptionByCustomer(customerId: string, patch: Partial<StoredUser>) {
  const user = await findUserByStripeCustomer(customerId);
  if (!user) return;
  const updated = { ...user, ...patch, updatedAt: new Date().toISOString() } as StoredUser;
  await writeJsonFile(userPath(user.id), updated);
}


app.post("/api/create-checkout-session", async (c) => {
  const current = await getAccountForRequest(c);
  if (current instanceof Response) return current;
  const { user, account } = current;
  const body = await c.req.json().catch(() => ({}));

  let priceId: string;
  if (body.priceId && body.priceId.startsWith("price_")) {
    priceId = body.priceId;
  } else {
    const priceKey = body.priceId === "price_yearly" || body.priceId === "yearly" ? "yearly" : "monthly";
    priceId = await ensureStripeProductAndPrice(priceKey);
  }

  try {
    const customerEmail = user.email || account.email;
    const successUrl = `${getBaseUrl(c)}/billing/success?session_id={CHECKOUT_SESSION_ID}`;
    const cancelUrl = `${getBaseUrl(c)}/pricing?canceled=1`;
    const params = new URLSearchParams({
      mode: "subscription",
      success_url: successUrl,
      cancel_url: cancelUrl,
      "line_items[0][price]": priceId,
      "line_items[0][quantity]": "1",
      "metadata[userId]": user.id,
      "metadata[email]": customerEmail,
      "metadata[priceId]": priceId,
      "subscription_data[metadata][userId]": user.id,
      "subscription_data[metadata][priceId]": priceId,
      allow_promotion_codes: "true",
    });
    if (account.stripeCustomerId) params.set("customer", account.stripeCustomerId);
    else if (customerEmail) params.set("customer_email", customerEmail);
    const resp = await stripeRequest("/checkout/sessions", { method: "POST", body: params });
    const data = await resp.json() as any;
    if (!resp.ok) return c.json({ error: data?.error?.message || "Stripe checkout failed" }, 502);
    if (data.customer && !account.stripeCustomerId) {
      await writeJsonFile(userPath(user.id), { ...account, stripeCustomerId: data.customer, updatedAt: new Date().toISOString() });
    }
    return c.json({ url: data.url });
  } catch (error: any) {
    console.error("Checkout failed:", error);
    return c.json({ error: error.message || "Checkout failed" }, 502);
  }
});

app.post("/api/stripe-webhook", async (c) => {
  const webhookSecret = await readEnv("STRIPE_WEBHOOK_SECRET");
  const sig = c.req.header("stripe-signature") || "";
  const rawBody = await c.req.text();
  if (!webhookSecret || !sig) return c.json({ error: "Missing webhook secret/signature" }, 400);
  const stripeMod = await import("stripe");
  let event: any;
  try {
    const StripeCtor = (stripeMod.default || stripeMod) as any;
    const client = new StripeCtor(await readEnv("STRIPE_SECRET_KEY"));
    event = await client.webhooks.constructEventAsync(rawBody, sig, webhookSecret);
  } catch (error: any) {
    console.error("Stripe webhook verification failed:", error.message);
    return c.json({ error: "Invalid signature" }, 400);
  }

  try {
    if (event.type === "checkout.session.completed") {
      const session = event.data.object;
      const userId = session.metadata?.userId;
      const paidPriceId = session.metadata?.priceId || "";
      const detectedPlan = PRICE_TO_PLAN[paidPriceId] || "pro";
      if (userId) {
        const existing = await readJsonFile<StoredUser | null>(userPath(userId), null);
        if (existing) {
          await writeJsonFile(userPath(userId), {
            ...existing,
            plan: detectedPlan,
            stripePriceId: paidPriceId,
            stripeCustomerId: String(session.customer || existing.stripeCustomerId || ""),
            subscriptionId: String(session.subscription || existing.subscriptionId || ""),
            subscriptionStatus: "active",
            trialStart: null as any,
            trialEnd: null as any,
            updatedAt: new Date().toISOString(),
          });
        }
      }
    }
    if (event.type === "customer.subscription.updated" || event.type === "customer.subscription.deleted") {
      const subscription = event.data.object;
      const customerId = String(subscription.customer || "");
      const active = ["active", "trialing"].includes(subscription.status);
      const subPriceId = subscription.items?.data?.[0]?.price?.id || subscription.metadata?.priceId || "";
      const detectedPlan = PRICE_TO_PLAN[subPriceId] || "pro";
      await updateUserSubscriptionByCustomer(customerId, { trialStart: null as any, trialEnd: null as any,
        plan: active ? detectedPlan : "free",
        stripePriceId: subPriceId,
        subscriptionId: String(subscription.id || ""),
        subscriptionStatus: String(subscription.status || ""),
        currentPeriodEnd: Number(subscription.current_period_end || 0),
      });
    }
  } catch (error) {
    console.error("Stripe webhook processing failed:", error);
    return c.json({ error: "Webhook processing failed" }, 500);
  }
  return c.json({ received: true });
});

app.get("/api/billing/verify-session", async (c) => {
  const sessionId = c.req.query("session_id");
  if (!sessionId) return c.json({ error: "Missing session_id" }, 400);
  const current = await getAccountForRequest(c);
  if (current instanceof Response) return current;
  const { user, account } = current;
  try {
    const resp = await stripeRequest(`/checkout/sessions/${sessionId}?expand[]=subscription`);
    if (!resp.ok) return c.json({ error: "Could not retrieve session" }, 502);
    const session = await resp.json() as any;
    if (session.payment_status !== "paid") return c.json({ upgraded: false, status: session.payment_status });
    const updated = {
      ...account,
      plan: (PRICE_TO_PLAN[session.subscription?.items?.data?.[0]?.price?.id || ""] || "pro") as StoredUser["plan"],
      stripePriceId: session.subscription?.items?.data?.[0]?.price?.id || "",
      stripeCustomerId: String(session.customer || account.stripeCustomerId || ""),
      subscriptionId: String(session.subscription?.id || session.subscription || account.subscriptionId || ""),
      subscriptionStatus: "active",
      currentPeriodEnd: session.subscription?.current_period_end || account.currentPeriodEnd || null,
      updatedAt: new Date().toISOString(),
    };
    await writeJsonFile(userPath(user.id), updated);
    return c.json({ upgraded: true, plan: updated.plan, subscriptionStatus: "active" });
  } catch (e: any) {
    console.error("Verify session error:", e);
    return c.json({ error: "Verification failed" }, 502);
  }
});

app.post("/api/cancel-subscription", async (c) => {
  const current = await getAccountForRequest(c);
  if (current instanceof Response) return current;
  const { user, account } = current;
  if (!account.subscriptionId) return c.json({ error: "No active subscription found" }, 400);
  try {
    const resp = await stripeRequest(`/subscriptions/${account.subscriptionId}`, {
      method: "POST",
      body: new URLSearchParams({ cancel_at_period_end: "true" }),
    });
    if (!resp.ok) {
      const err = await resp.json() as any;
      return c.json({ error: err?.error?.message || "Cancel failed" }, 502);
    }
    const sub = await resp.json() as any;
    const updated = {
      ...account,
      subscriptionStatus: "canceling",
      currentPeriodEnd: sub.current_period_end || account.currentPeriodEnd || null,
      updatedAt: new Date().toISOString(),
    };
    await writeJsonFile(userPath(user.id), updated);
    return c.json({ canceled: true, currentPeriodEnd: updated.currentPeriodEnd });
  } catch (e: any) {
    console.error("Cancel subscription error:", e);
    return c.json({ error: "Cancel failed" }, 502);
  }
});

app.post("/api/billing/sync-subscription", async (c) => {
  const current = await getAccountForRequest(c);
  if (current instanceof Response) return current;
  const { user, account } = current;

  let stripeCustomerId = account.stripeCustomerId;
  let subscriptionId = account.subscriptionId;

  // Step 1: if no customer ID, search Stripe by email
  if (!stripeCustomerId) {
    const searchResp = await stripeRequest(`/customers/search?query=email:'${encodeURIComponent(user.email)}'&limit=1`);
    if (searchResp.ok) {
      const searchData = await searchResp.json() as any;
      stripeCustomerId = searchData?.data?.[0]?.id;
    }
  }

  // Step 2: if still no customer, nothing to sync
  if (!stripeCustomerId) {
    return c.json({ synced: false, message: "No Stripe account found for this email. If you just paid, please wait a moment and try again." });
  }

  // Step 3: get active subscription for this customer
  if (!subscriptionId) {
    const subResp = await stripeRequest(`/subscriptions?customer=${stripeCustomerId}&limit=1&status=active`);
    if (subResp.ok) {
      const subData = await subResp.json() as any;
      subscriptionId = subData?.data?.[0]?.id;
    }
  }

  if (!subscriptionId) {
    // Check canceled/past_due too
    const subResp2 = await stripeRequest(`/subscriptions?customer=${stripeCustomerId}&limit=1`);
    if (subResp2.ok) {
      const subData2 = await subResp2.json() as any;
      subscriptionId = subData2?.data?.[0]?.id;
    }
  }

  if (!subscriptionId) {
    return c.json({ synced: false, message: "No subscription found for this account. If you just paid, please wait a moment and try again." });
  }

  // Step 4: fetch subscription details and update local account
  const subResp = await stripeRequest(`/subscriptions/${subscriptionId}`);
  if (!subResp.ok) return c.json({ error: "Could not retrieve subscription from Stripe" }, 502);
  const sub = await subResp.json() as any;

  const isActive = ["active", "trialing"].includes(sub.status);
  const updated: StoredUser = {
    ...account,
    stripeCustomerId,
    subscriptionId,
    plan: isActive ? "pro" : account.plan,
    subscriptionStatus: sub.status,
    currentPeriodEnd: sub.current_period_end ?? null,
    updatedAt: new Date().toISOString(),
  };
  await writeJsonFile(userPath(user.id), updated);

  return c.json({
    synced: true,
    plan: updated.plan,
    subscriptionStatus: sub.status,
    currentPeriodEnd: sub.current_period_end,
    message: isActive ? "Your Pro subscription is active!" : `Subscription status: ${sub.status}`,
  });
});


export default app;
