import { Hono } from "hono";
import { ensureDir, readJsonFile, writeJsonFile } from "../lib/storage";
import { authorizeAi, getAccountForRequest, getCurrentUser, getPlanTier, isPlatformAdmin } from "../lib/auth-helpers";
import { cleanLocalModelOutput, getZoToken, selectOllamaModel } from "../lib/maia";
import { DEFAULT_PRO_MODEL, generatedToolHistoryDir, generatedToolsDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for clinical

const app = new Hono();




app.post("/api/clinical/interactions", async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const raw = Array.isArray(body.drugs) ? body.drugs : splitDrugList(body.drugs || body.input || "");
  const drugs = [...new Set(raw.map(normalizeDrugName).filter(Boolean))].slice(0, 10);
  if (drugs.length < 2) return c.json({ error: "Enter at least two drugs" }, 400);

  const [rxInteractions, labelWarnings] = await Promise.all([
    fetchRxNormInteractions(drugs),
    fetchOpenFdaLabelWarnings(drugs),
  ]);

  const severities = rxInteractions.map((i) => i.severity);
  const highest = severities.includes("high") ? "critical"
    : severities.includes("moderate") ? "major"
    : severities.includes("low") ? "moderate"
    : "none found";

  return c.json({
    drugs,
    interactionCount: rxInteractions.length,
    highestSeverity: rxInteractions.length ? highest : "none found",
    interactions: rxInteractions,
    labelResults: labelWarnings,
    disclaimer: "Educational screening only. Not a substitute for pharmacist/prescriber review or clinical judgment.",
  });
});

app.post("/api/clinical/dosing", async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const drug = normalizeDrugName(String(body.drug || ""));
  if (!drug) return c.json({ error: "Drug name required" }, 400);
  const weightKg = Number(body.weightKg || 0);

  const [label, ndcProducts] = await Promise.all([
    fetchLabel(drug),
    (async () => {
      try {
        const ndcResp = await fetch(
          `https://api.fda.gov/drug/ndc.json?search=openfda.generic_name:${drug}&limit=50`
        );
        return ndcResp.ok ? (await ndcResp.json()).results || [] : [];
      } catch {
        return [];
      }
    })(),
  ]);

  const dosageText = asText(firstLabelValue(label, "dosage_and_administration"));
  const mgKgMatches: any[] = [];
  for (const m of [...dosageText.matchAll(/(\d+(?:\.\d+)?)\s*(?:to|-|–)?\s*(\d+(?:\.\d+)?)?\s*mg\s*\/\s*kg/gi)].slice(0, 10)) {
    const row: any = { lowMgPerKg: Number(m[1]), highMgPerKg: m[2] ? Number(m[2]) : null };
    if (weightKg > 0) {
      row.exampleForWeightKg = { lowMg: +(Number(m[1]) * weightKg).toFixed(2) };
      if (m[2]) row.exampleForWeightKg.highMg = +(Number(m[2]) * weightKg).toFixed(2);
    }
    mgKgMatches.push(row);
  }

  const sentences = dosageText.split(/(?<=[.!?])\s+/).filter(
    (s) => /\bmg\b|\b dose\b|\bdaily\b|\btablet\b|\binjection\b|\bevery\b|\bhours\b/i.test(s)
  ).slice(0, 16);

  const routes = [...new Set(ndcProducts.map((p: any) => p.route).filter(Boolean))];
  const routeSpecificForms = routes.length
    ? routes.map((r: string) => `${r}: ${ndcProducts.filter((p: any) => p.route === r).map((p: any) => p.brand_name || p.generic_name || "NDC product").slice(0, 3).join(", ")}`)
    : [];

  return c.json({
    drug,
    weightKg: weightKg || null,
    mgPerKgFindings: mgKgMatches,
    dosingLabelAvailable: Boolean(dosageText),
    dosageAndAdministration: dosageText || "No dosage_and_administration field found in FDA label.",
    adultDoseSnippets: sentences,
    routeSpecificForms,
    warning: "Dosing helper extracts FDA label text only. Does not prescribe, adjust for renal/hepatic function, or replace institutional protocols.",
  });
});

app.post("/api/clinical/cascade", async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const drugs = [...new Set(splitDrugList(body.drugs || body.input))].slice(0, 10);
  if (drugs.length < 2) return c.json({ error: "Enter at least two drugs" }, 400);
  const nodes = drugs.map((drug) => ({ drug, ...(cypKnowledge[drug] || { enzymes: [], effects: [], notes: "No local CYP/P-gp profile yet." }) }));
  const cascades: any[] = [];
  for (let i = 0; i < nodes.length; i++) {
    for (let j = i + 1; j < nodes.length; j++) {
      const a = nodes[i];
      const b = nodes[j];
      const shared = a.enzymes.filter((e) => b.enzymes.includes(e));
      const known = interactionKnowledge.find((item) => item.drugs.every((d) => d === a.drug || d === b.drug));
      if (shared.length || known) cascades.push({ drugs: [a.drug, b.drug], sharedPathways: shared, severity: known?.severity || (shared.length ? "possible" : "none"), explanation: known?.mechanism || `Both drugs share ${shared.join(", ")}; assess for inhibition/induction/substrate competition depending on full medication context.` });
    }
  }
  return c.json({
    drugs,
    nodes,
    cascades,
    cascadeCount: cascades.length,
    source: "Zo local MEDGRAPH-style cascade fallback using CYP/P-gp knowledge plus known interaction rules. External MEDGRAPH repo was inspected but not embedded as a service yet.",
    disclaimer: "Educational cascade screening only. Requires pharmacist/prescriber verification.",
  });
});


type GeneratedToolPayload = {
  id: string;
  name: string;
  description: string;
  category: string;
  kind: "calculator" | "reference";
  fields?: Array<{ id: string; label: string; type: "number" | "text" | "select"; unit?: string; placeholder?: string; options?: string[]; min?: number; max?: number }>;
  formulas?: Array<{ id: string; label: string; expression: string; unit?: string; precision?: number; normalRange?: string; explanation?: string }>;
  sections?: Array<{ title: string; content?: string; bullets?: string[] }>;
  disclaimer?: string;
};

function slugifyTool(value: string): string {
  const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
  return slug || `tool-${Date.now()}`;
}

async function ensureGeneratedToolsDir() {
  await mkdir(generatedToolsDir, { recursive: true });
}

function extractJsonObject(text: string): any {
  const trimmed = text.trim();
  try { return JSON.parse(trimmed); } catch {}
  const match = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (match) return JSON.parse(match[1]);
  const start = trimmed.indexOf("{");
  const end = trimmed.lastIndexOf("}");
  if (start >= 0 && end > start) return JSON.parse(trimmed.slice(start, end + 1));
  throw new Error("AI did not return JSON");
}

function sanitizeGeneratedTool(raw: any, request: string, tier: "free" | "pro", model: string): GeneratedToolPayload & { createdAt: string; sourceTier: "free" | "pro"; model: string } {
  const name = String(raw?.name || request || "Generated Clinical Tool").trim().slice(0, 80);
  const id = slugifyTool(raw?.id || name);
  const kind = raw?.kind === "reference" ? "reference" : "calculator";
  const fields = Array.isArray(raw?.fields) ? raw.fields.slice(0, 12).map((field: any) => ({
    id: slugifyTool(String(field.id || field.label || "field")).replace(/-/g, "_"),
    label: String(field.label || field.id || "Input").slice(0, 80),
    type: ["number", "text", "select"].includes(field.type) ? field.type : "number",
    unit: field.unit ? String(field.unit).slice(0, 24) : undefined,
    placeholder: field.placeholder ? String(field.placeholder).slice(0, 100) : undefined,
    options: Array.isArray(field.options) ? field.options.map(String).slice(0, 12) : undefined,
    min: typeof field.min === "number" ? field.min : undefined,
    max: typeof field.max === "number" ? field.max : undefined,
  })) : [];
  const fieldIds = new Set(fields.map((f: any) => f.id));
  const formulas = Array.isArray(raw?.formulas) ? raw.formulas.slice(0, 8).map((formula: any) => ({
    id: slugifyTool(String(formula.id || formula.label || "result")).replace(/-/g, "_"),
    label: String(formula.label || formula.id || "Result").slice(0, 80),
    expression: String(formula.expression || "0").replace(/[^A-Za-z0-9_()+\-*/.\s]/g, "").slice(0, 240),
    unit: formula.unit ? String(formula.unit).slice(0, 24) : undefined,
    precision: Number.isFinite(Number(formula.precision)) ? Math.max(0, Math.min(6, Number(formula.precision))) : 2,
    normalRange: formula.normalRange ? String(formula.normalRange).slice(0, 120) : undefined,
    explanation: formula.explanation ? String(formula.explanation).slice(0, 360) : undefined,
  })).filter((formula: any) => {
    const identifiers = formula.expression.match(/[A-Za-z_][A-Za-z0-9_]*/g) || [];
    return identifiers.every((id: string) => fieldIds.has(id));
  }) : [];
  const sections = Array.isArray(raw?.sections) ? raw.sections.slice(0, 8).map((section: any) => ({
    title: String(section.title || "Notes").slice(0, 80),
    content: section.content ? String(section.content).slice(0, 1200) : undefined,
    bullets: Array.isArray(section.bullets) ? section.bullets.map((b: any) => String(b).slice(0, 260)).slice(0, 12) : undefined,
  })) : [];
  return {
    id,
    name,
    description: String(raw?.description || `AI-generated clinical tool for: ${request}`).slice(0, 240),
    category: String(raw?.category || "Nursing").slice(0, 60),
    kind,
    fields: kind === "calculator" ? fields : [],
    formulas: kind === "calculator" ? formulas : [],
    sections,
    disclaimer: String(raw?.disclaimer || "Educational screening only. Verify calculations, ranges, and clinical decisions with program policy, facility policy, and clinical judgment.").slice(0, 360),
    createdAt: new Date().toISOString(),
    sourceTier: tier,
    model,
  };
}

function buildToolPrompt(request: string) {
  return `Create one safe nursing education clinical tool as STRICT JSON only. Do not include markdown fences or commentary.

User request: ${request}

Return this JSON schema:
{
  "name": "short tool name",
  "description": "what it does",
  "category": "Pharmacology | Skills | Safety | Dosage | Pediatrics | Med-Surg | Psych | Other",
  "kind": "calculator" or "reference",
  "fields": [{"id":"snake_case", "label":"Input label", "type":"number|text|select", "unit":"optional", "placeholder":"optional", "options":["only for select"]}],
  "formulas": [{"id":"snake_case", "label":"Result label", "expression":"math expression using field ids only, operators + - * / parentheses", "unit":"optional", "precision":2, "normalRange":"optional", "explanation":"brief rationale"}],
  "sections": [{"title":"section title", "content":"short paragraph", "bullets":["safe nursing note"]}],
  "disclaimer":"educational safety disclaimer"
}

Rules:
- For calculators, include numeric fields and formulas when clinically appropriate.
- Use only arithmetic expressions with field ids. No JavaScript, no functions, no comparisons.
- Do not invent medication orders that look like prescriptions.
- Include nursing safety notes and when to verify with instructor/pharmacy/provider.
- If the requested tool is unsafe for automation, make a reference/checklist tool instead.`;
}

async function generateToolWithOllama(request: string) {
  const selected = selectOllamaModel();
  const response = await fetch("http://127.0.0.1:11434/api/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: selected.model,
      stream: false,
      messages: [
        { role: "system", content: "You generate strict JSON for safe nursing education tools. Output JSON only." },
        { role: "user", content: buildToolPrompt(request) },
      ],
      options: { ...selected.options, temperature: 0.1 },
    }),
  });
  if (!response.ok) throw new Error("Local Ollama tool generation failed");
  const data = await response.json() as { message?: { content?: string }; response?: string };
  return { text: cleanLocalModelOutput(data.message?.content || data.response || ""), model: `ollama:${selected.model}` };
}

async function generateToolWithZoAsk(request: string, forcedModel?: string) {
  const token = await getZoToken();
  if (!token) throw new Error("Zo API token unavailable for Pro model");
  const model = forcedModel || process.env.MAIA_PRO_MODEL || DEFAULT_PRO_MODEL;
  const response = await fetch("https://api.zo.computer/zo/ask", {
    method: "POST",
    headers: { "Authorization": token, "Content-Type": "application/json", "Accept": "application/json" },
    body: JSON.stringify({ input: buildToolPrompt(request), model_name: model }),
  });
  if (!response.ok) throw new Error(`Zo Ask tool generation failed: ${response.status}`);
  const data = await response.json() as { output?: string };
  return { text: data.output || "", model };
}

app.get("/api/clinical/generated-tools", async (c) => {
  await ensureGeneratedToolsDir();
  const files = (await readdir(generatedToolsDir)).filter((file) => file.endsWith(".json"));
  const currentUser = getCurrentUser(c);
  const admin = isPlatformAdmin(currentUser);
  const tools = await Promise.all(files.map(async (file) => {
    try { return JSON.parse(await readFile(path.join(generatedToolsDir, file), "utf8")); } catch { return null; }
  }));
  const visibleTools = tools.filter(Boolean).filter((tool: any) => {
    const status = tool.status || "approved";
    return status === "approved" || admin || (currentUser && tool.ownerId === currentUser.id);
  });
  return c.json({ tools: visibleTools.sort((a: any, b: any) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))) });
});

app.post("/api/clinical/generate-tool", async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const request = String(body.request || "").trim().slice(0, 1000);
  const tier = body.tier === "pro" ? "pro" : "free";
  if (!request) return c.json({ error: "Describe the clinical tool you want to generate." }, 400);

  const auth = await authorizeAi(c, tier, "toolBuilder");
  if (auth instanceof Response) return auth;

  const toolTier = getPlanTier(auth.account);
  const toolLimit = getToolLimit(toolTier);
  await ensureGeneratedToolsDir();
  const existingTools = await readdir(generatedToolsDir).catch(() => [] as string[]);
  const userTools = existingTools.filter(f => f.endsWith(".json"));
  let userToolCount = 0;
  for (const f of userTools) {
    try {
      const t = JSON.parse(await readFile(path.join(generatedToolsDir, f), "utf8"));
      if (t.ownerId === auth.user.id) userToolCount++;
    } catch {}
  }
  if (userToolCount >= toolLimit && !isPlatformAdmin(auth.user)) {
    return c.json({ error: `Your plan allows up to ${toolLimit} generated tools. Delete an existing tool to create a new one.`, upgradeRequired: true }, 402);
  }

  try {
    const generated = await generateToolWithZoAsk(request, auth.model);
    const raw = extractJsonObject(generated.text);
    const tool = { ...sanitizeGeneratedTool(raw, request, tier, generated.model), ownerId: auth.user.id, ownerEmail: auth.user.email, status: "pending", reviewedAt: null };
    await ensureGeneratedToolsDir();
    await writeFile(path.join(generatedToolsDir, `${tool.id}.json`), JSON.stringify(tool, null, 2));
    return c.json({ tool, pendingReview: true });
  } catch (error: any) {
    console.error("Generated clinical tool failed:", error);
    return c.json({ error: error.message || "Tool generation failed" }, 502);
  }
});

app.post("/api/clinical/generated-tools/:id/modify", async (c) => {
  const id = slugifyTool(c.req.param("id"));
  const body = await c.req.json().catch(() => ({}));
  const instruction = String(body.instruction || "").trim().slice(0, 1000);
  const tier = body.tier === "pro" ? "pro" : "free";
  if (!instruction) return c.json({ error: "Describe how to modify this tool." }, 400);

  try {
    await ensureGeneratedToolsDir();
    const filePath = path.join(generatedToolsDir, `${id}.json`);
    const existingTool = JSON.parse(await readFile(filePath, "utf8"));
    const auth = await authorizeAi(c, tier, "toolBuilder");
    if (auth instanceof Response) return auth;
    const generated = await generateModifiedToolWithZoAsk(existingTool, instruction, auth.model);
    const raw = extractJsonObject(generated.text);
    await ensureDir(generatedToolHistoryDir);
    const historyPath = path.join(generatedToolHistoryDir, `${existingTool.id}.json`);
    const history = await readJsonFile<any[]>(historyPath, []);
    history.push({ ...existingTool, archivedAt: new Date().toISOString() });
    await writeJsonFile(historyPath, history.slice(-25));
    const tool = { ...sanitizeGeneratedTool({ ...raw, id: existingTool.id }, instruction, tier, generated.model), ownerId: existingTool.ownerId || auth.user.id, ownerEmail: existingTool.ownerEmail || auth.user.email, status: "pending", reviewedAt: null };
    tool.createdAt = existingTool.createdAt || tool.createdAt;
    (tool as any).updatedAt = new Date().toISOString();
    await writeFile(filePath, JSON.stringify(tool, null, 2));
    return c.json({ tool, pendingReview: true });
  } catch (error: any) {
    console.error("Modify generated clinical tool failed:", error);
    return c.json({ error: error.message || "Tool modification failed" }, 502);
  }
});

type NclexQuestionPayload = {
  type: "mcq" | "sata";
  topic: string;
  difficulty: "easy" | "medium" | "hard";
  stem: string;
  options: Array<{ id: string; text: string }>;
  correctAnswers: string[];
  rationale: string;
  optionRationales: Record<string, string>;
};

function buildNclexQuestionPrompt(topic: string, options?: { tutorMode?: boolean; focusCategory?: string; focusSystem?: string }) {
  const focusLines: string[] = [];
  if (options?.focusSystem) focusLines.push(`- Body system focus: ${options.focusSystem}`);
  if (options?.focusCategory) focusLines.push(`- NCLEX category focus: ${options.focusCategory}`);
  const focusBlock = focusLines.length ? `\nFocus constraints:\n${focusLines.join("\n")}\n` : "";
  const tutorNote = options?.tutorMode
    ? `- Always populate optionRationales with detailed per-option reasoning (2-3 sentences each) explaining why each option is correct or incorrect — this is critical for tutor mode.\n`
    : `- Include brief optionRationales for each option.\n`;

  return `Create one NCLEX-style nursing practice question as STRICT JSON only. Do not include markdown fences or commentary.

Requested topic: ${topic}${focusBlock}

Return this exact JSON shape:
{
  "type": "mcq" or "sata",
  "topic": "short topic label",
  "difficulty": "easy" | "medium" | "hard",
  "stem": "question stem with nursing scenario when appropriate",
  "options": [{"id":"A","text":"answer choice"},{"id":"B","text":"answer choice"},{"id":"C","text":"answer choice"},{"id":"D","text":"answer choice"}],
  "correctAnswers": ["A"],
  "rationale": "why the correct answer set is best",
  "optionRationales": {"A":"why A is correct/incorrect","B":"why B is correct/incorrect","C":"why C is correct/incorrect","D":"why D is correct/incorrect"}
}

Rules:
${tutorNote}- Make either a standard multiple-choice question (mcq, exactly one correct answer) or select-all-that-apply (sata, two or more correct answers).
- Keep options plausible and nursing-specific.
- Include pharmacology, prioritization, safety, psych, med-surg, fundamentals, maternal-child, pediatrics, or mental health as appropriate to the requested topic.
- Do not include all/none of the above.
- Do not make the answer ambiguous.
- Use current nursing education framing and NCLEX-style safety/prioritization logic.
- Educational use only; avoid patient-specific medical advice.`;
}

function sanitizeNclexQuestion(raw: any, requestedTopic: string): NclexQuestionPayload {
  const type = raw?.type === "sata" ? "sata" : "mcq";
  const optionSource = Array.isArray(raw?.options) ? raw.options : [];
  const options = optionSource.slice(0, 6).map((option: any, index: number) => ({
    id: String(option?.id || String.fromCharCode(65 + index)).trim().toUpperCase().slice(0, 1),
    text: String(option?.text || option || "").trim().slice(0, 260),
  })).filter((option: any) => /^[A-F]$/.test(option.id) && option.text);
  while (options.length < 4) {
    const id = String.fromCharCode(65 + options.length);
    options.push({ id, text: `Option ${id}` });
  }
  const optionIds = new Set(options.map((option: any) => option.id));
  let correctAnswers = Array.isArray(raw?.correctAnswers) ? raw.correctAnswers.map((v: any) => String(v).trim().toUpperCase().slice(0, 1)).filter((id: string) => optionIds.has(id)) : [];
  correctAnswers = Array.from(new Set(correctAnswers));
  if (type === "mcq" && correctAnswers.length !== 1) correctAnswers = [options[0].id];
  if (type === "sata" && correctAnswers.length < 2) correctAnswers = options.slice(0, 2).map((option: any) => option.id);
  const rawRationales = raw?.optionRationales && typeof raw.optionRationales === "object" ? raw.optionRationales : {};
  const optionRationales: Record<string, string> = {};
  for (const option of options) {
    optionRationales[option.id] = String(rawRationales[option.id] || `${option.id} is ${correctAnswers.includes(option.id) ? "part of" : "not part of"} the best answer set.`).slice(0, 420);
  }
  return {
    type,
    topic: String(raw?.topic || requestedTopic || "NCLEX practice").slice(0, 80),
    difficulty: ["easy", "medium", "hard"].includes(raw?.difficulty) ? raw.difficulty : "medium",
    stem: String(raw?.stem || `Which answer is best for ${requestedTopic || "this nursing topic"}?`).trim().slice(0, 900),
    options,
    correctAnswers,
    rationale: String(raw?.rationale || "Review the option rationales for why the answer set is best.").slice(0, 1200),
    optionRationales,
  };
}

async function generateNclexQuestionWithOllama(topic: string) {
  const selected = selectOllamaModel();
  const response = await fetch("http://127.0.0.1:11434/api/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: selected.model,
      stream: false,
      messages: [
        { role: "system", content: "You generate strict JSON for NCLEX-style nursing education questions. Output JSON only." },
        { role: "user", content: buildNclexQuestionPrompt(topic) },
      ],
      options: { ...selected.options, temperature: 0.2 },
    }),
  });
  if (!response.ok) throw new Error("Free MAIA question generation failed");
  const data = await response.json() as { message?: { content?: string }; response?: string };
  return cleanLocalModelOutput(data.message?.content || data.response || "");
}

async function generateNclexQuestionWithZoAsk(topic: string, forcedModel?: string, options?: { tutorMode?: boolean; focusCategory?: string; focusSystem?: string }) {
  const token = await getZoToken();
  if (!token) throw new Error("Pro MAIA token unavailable");
  const model = forcedModel || process.env.MAIA_PRO_MODEL || DEFAULT_PRO_MODEL;
  const prompt = buildNclexQuestionPrompt(topic, options);
  const response = await fetch("https://api.zo.computer/zo/ask", {
    method: "POST",
    headers: { "Authorization": token, "Content-Type": "application/json", "Accept": "application/json" },
    body: JSON.stringify({ input: prompt, model_name: model }),
  });
  if (!response.ok) throw new Error(`Pro MAIA question generation failed: ${response.status}`);
  const data = await response.json() as { output?: string };
  return data.output || "";
}

app.post("/api/clinical/nclex-question", async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const topic = String(body.topic || "comprehensive nursing practice").trim().slice(0, 300) || "comprehensive nursing practice";
  const tier = body.tier === "pro" ? "pro" : "free";

  const resolved = await getAccountForRequest(c);
  const accountTier = resolved instanceof Response ? "free" : getPlanTier((resolved as any).account);
  const tutorMode = accountTier === "pro_plus" || accountTier === "max" ? Boolean(body.tutorMode) : false;
  const focusCategory = (accountTier === "max") ? String(body.focusCategory || "").trim().slice(0, 100) : "";
  const focusSystem = (accountTier === "max") ? String(body.focusSystem || "").trim().slice(0, 100) : "";
  try {
    const auth = await authorizeAi(c, tier, "messages");
    if (auth instanceof Response) return auth;
    const text = await generateNclexQuestionWithZoAsk(topic, auth.model, { tutorMode, focusCategory, focusSystem });
    const raw = extractJsonObject(text);
    return c.json({ question: sanitizeNclexQuestion(raw, topic), tier });
  } catch (error: any) {
    console.error("NCLEX question generation failed:", error);
    return c.json({ error: error.message || "Question generation failed" }, 502);
  }
});

app.post("/api/clinical/decision", async (c) => {


export default app;
