import { Hono } from "hono";
import { readJsonFile, safeId, writeJsonFile } from "../lib/storage";
import { isPlatformAdmin, requireCurrentUser } from "../lib/auth-helpers";
import { communityDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for community

const app = new Hono();

// ── Community Hub ─────────────────────────────────────────────────────────────
type CommunityThread = {
  id: string;
  title: string;
  content: string;
  userId: string;
  userName: string;
  userPicture?: string;
  category: string;
  commentCount: number;
  createdAt: string;
  updatedAt: string;
};
type CommunityComment = {
  id: string;
  userId: string;
  userName: string;
  userPicture?: string;
  body: string;
  createdAt: string;
};
function communityThreadsFile() { return path.join(communityDir, "threads.json"); }
function communityCommentsFile(threadId: string) { return path.join(communityDir, "comments", `${safeId(threadId)}.json`); }

async function getCommunityThreads(): Promise<CommunityThread[]> {
  return readJsonFile<CommunityThread[]>(communityThreadsFile(), []);
}

async function saveCommunityThread(thread: CommunityThread) {
  const threads = await getCommunityThreads();
  threads.unshift(thread);
  await writeJsonFile(communityThreadsFile(), threads);
  return thread;
}

async function getCommunityComments(threadId: string): Promise<CommunityComment[]> {
  return readJsonFile<CommunityComment[]>(communityCommentsFile(threadId), []);
}

async function saveCommunityComment(threadId: string, comment: CommunityComment) {
  const threads = await getCommunityThreads();
  const idx = threads.findIndex(t => t.id === threadId);
  if (idx !== -1) {
    threads[idx].commentCount = (threads[idx].commentCount || 0) + 1;
    threads[idx].updatedAt = new Date().toISOString();
    await writeJsonFile(communityThreadsFile(), threads);
  }
  const threadComments = await getCommunityComments(threadId);
  threadComments.push(comment);
  await writeJsonFile(communityCommentsFile(threadId), threadComments);
  return comment;
}


app.get("/api/community/threads", async (c) => {
  const threads = await getCommunityThreads();
  return c.json({ threads: threads.slice(0, 20) });
});

app.get("/api/community/threads/:id", async (c) => {
  const id = c.req.param("id");
  const threads = await getCommunityThreads();
  const thread = threads.find(t => t.id === id);
  if (!thread) return c.json({ error: "Thread not found" }, 404);
  const comments = await getCommunityComments(id);
  return c.json({ thread, comments });
});

app.post("/api/community/threads", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to post." }, 401);
  const body = await c.req.json().catch(() => ({}));
  const title = String(body.title || "").trim().slice(0, 200);
  const bodyText = String(body.body || "").trim().slice(0, 5000);
  const category = ["pharmacology","nclex","clinical","school","career","general"].includes(body.category) ? body.category : "general";
  if (!title || !bodyText) return c.json({ error: "Title and body required." }, 400);
  const now = new Date().toISOString();
  const thread: CommunityThread = {
    id: `thread_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`,
    userId: user.id,
    userName: user.name || user.email,
    userPicture: (user as any).picture || undefined,
    title,
    body: bodyText,
    category,
    commentCount: 0,
    createdAt: now,
    updatedAt: now,
  };
  await saveCommunityThread(thread);
  return c.json({ thread });
});

app.post("/api/community/threads/:id/comments", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to comment." }, 401);
  const threadId = c.req.param("id");
  const body = await c.req.json().catch(() => ({}));
  const bodyText = String(body.body || "").trim().slice(0, 2000);
  if (!bodyText) return c.json({ error: "Comment body required." }, 400);
  const comment: CommunityComment = {
    id: `cmt_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`,
    userId: user.id,
    userName: user.name || user.email,
    userPicture: (user as any).picture || undefined,
    body: bodyText,
    createdAt: new Date().toISOString(),
  };
  await saveCommunityComment(threadId, comment);
  return c.json({ comment });
});

app.delete("/api/community/threads/:id", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to manage threads." }, 401);
  if (!isPlatformAdmin(user)) return c.json({ error: "Admin only." }, 403);
  const threadId = c.req.param("id");
  const threads = await getCommunityThreads();
  const filtered = threads.filter(t => t.id !== threadId);
  if (filtered.length === threads.length) return c.json({ error: "Thread not found." }, 404);
  await writeJsonFile(communityThreadsFile(), filtered);
  return c.json({ ok: true });
});


export default app;
