import { Hono } from "hono";
import { ensureDir, readJsonFile } from "../lib/storage";
import { getCurrentUser } from "../lib/auth-helpers";
import { saveConversationForUser } from "../lib/maia";
// <auto-generated from server.ts> — route module for conversations

const app = new Hono();


app.get("/api/conversations", async (c) => {
  const user = getCurrentUser(c);
  if (!user) return c.json({ conversations: [] });
  await ensureDir(conversationUserDir(user.id));
  const files = (await readdir(conversationUserDir(user.id)).catch(() => [])).filter((file) => file.endsWith(".json"));
  const records = await Promise.all(files.map(async (file) => readJsonFile<ConversationRecord | null>(path.join(conversationUserDir(user.id), file), null)));
  const conversations = records.filter(Boolean).map((record: any) => ({
    id: record.id,
    title: record.title,
    created_at: record.created_at,
    updated_at: record.updated_at,
  })).sort((a, b) => String(b.updated_at).localeCompare(String(a.updated_at)));
  return c.json({ conversations });
});

app.get("/api/conversations/:id", async (c) => {
  const user = getCurrentUser(c);
  if (!user) return c.json({ error: "Please sign in to load conversations." }, 401);
  const id = c.req.param("id");
  const record = await readJsonFile<ConversationRecord | null>(conversationPath(user.id, id), null);
  if (!record) return c.json({ error: "Conversation not found" }, 404);
  return c.json({ conversation: { id: record.id, title: record.title, created_at: record.created_at, updated_at: record.updated_at }, messages: record.messages });
});

app.post("/api/conversations", async (c) => {
  const user = getCurrentUser(c);
  if (!user) return c.json({ error: "Please sign in to save conversations." }, 401);
  const body = await c.req.json().catch(() => ({}));
  const messages = Array.isArray(body.messages) ? body.messages.filter((m: any) => (m?.role === "user" || m?.role === "assistant") && String(m?.content || "").trim()).map((m: any) => ({ role: m.role, content: String(m.content).trim() })) : [];
  if (!messages.length) return c.json({ error: "messages required" }, 400);
  const record = await saveConversationForUser(user.id, String(body.conversationId || ""), messages);
  return c.json({ conversation: { id: record.id, title: record.title, created_at: record.created_at, updated_at: record.updated_at }, messages: record.messages });
});

app.delete("/api/conversations/:id", async (c) => {
  const user = getCurrentUser(c);
  if (!user) return c.json({ error: "Please sign in to delete conversations." }, 401);
  const filePath = conversationPath(user.id, c.req.param("id"));
  try { await Bun.file(filePath).delete(); } catch {}
  return c.json({ ok: true });
});


let cachedDrugIndex: any | null = null;

async function loadDrugIndex() {
  if (cachedDrugIndex) return cachedDrugIndex;
  try {
    cachedDrugIndex = await Bun.file("./data/drug-index.json").json();
    return cachedDrugIndex;
  } catch (err) {
    console.error("Failed to load drug index:", err);
    return null;
  }
}

function publicDrugSummary(drug: any) {
  if (drug.entryName || drug.productNdc) {
    return {
      id: drug.id,
      entryName: drug.entryName,
      genericName: drug.genericName,
      canonicalGeneric: drug.canonicalGeneric,
      brandName: drug.brandName,
      brandNames: drug.brandName ? [drug.brandName] : [],
      routes: drug.routes || [],
      dosageForm: drug.dosageForm,
      dosageForms: drug.dosageForm ? [drug.dosageForm] : [],
      manufacturer: drug.manufacturer,
      productNdc: drug.productNdc,
      productType: drug.productType,
      marketingCategory: drug.marketingCategory,
      substances: drug.substances?.slice(0, 8) || [],
      pharmClasses: drug.pharmClasses?.slice(0, 8) || [],
      productCount: 1,
    };
  }
  return {
    id: drug.id,
    genericName: drug.genericName,
    brandNames: drug.brandNames?.slice(0, 8) || [],
    routes: drug.routes || [],
    dosageForms: drug.dosageForms || [],
    substances: drug.substances?.slice(0, 8) || [],
    productCount: drug.productCount || 0,
    pharmClasses: drug.pharmClasses?.slice(0, 8) || [],
  };
}


export default app;
