import { Hono } from "hono";
import { ensureDir, readJsonFile, safeId, writeJsonFile } from "../lib/storage";
import { authorizeAi, requireCurrentUser } from "../lib/auth-helpers";
import { MAIA_PROMPT, callZoAsk, callZoAskStream, checkGuestUsage, cleanLocalModelOutput, getClientIp, getZoToken, makeConversationTitle, saveConversationForUser, selectOllamaModel, validToken } from "../lib/maia";
import { conversationsDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for educator

const app = new Hono();

function conversationUserDir(userId: string) {
  return path.join(conversationsDir, safeId(userId));
}

function conversationPath(userId: string, conversationId: string) {
  return path.join(conversationUserDir(userId), `${safeId(conversationId)}.json`);
}

function makeConversationTitle(messages: Array<{ role: string; content: string }>): string {
  const firstUser = messages.find((m) => m.role === "user")?.content || "New MAIA conversation";
  return firstUser.replace(/\s+/g, " ").trim().slice(0, 56) || "New MAIA conversation";
}

async function saveConversationForUser(userId: string, conversationId: string | undefined, messages: Array<{ role: "user" | "assistant"; content: string }>): Promise<ConversationRecord> {
  await ensureDir(conversationUserDir(userId));
  const id = conversationId && /^[a-zA-Z0-9._-]{8,120}$/.test(conversationId) ? conversationId : `conv_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`;
  const existing = await readJsonFile<ConversationRecord | null>(conversationPath(userId, id), null);
  const now = new Date().toISOString();
  const record: ConversationRecord = {
    id,
    title: existing?.title || makeConversationTitle(messages),
    messages: messages.slice(-80).map((m) => ({ role: m.role, content: String(m.content || "").slice(0, 12000) })),
    created_at: existing?.created_at || now,
    updated_at: now,
  };
  await writeJsonFile(conversationPath(userId, id), record);
  return record;
}

function validToken(value: string | undefined): value is string {
  return Boolean(value && value !== "none" && !value.startsWith("$") && value.length > 20);
}

async function getZoToken(): Promise<string | null> {
  // ZO_API_KEY is the permanent long-lived token created in Settings > Advanced.
  // ZO_CLIENT_IDENTITY_TOKEN is a short-lived fallback (~24hr).
  const token = process.env.ZO_API_KEY || process.env.ZO_CLIENT_IDENTITY_TOKEN;
  if (validToken(token)) return token;
  return null;
}

const MAIA_PROMPT = `You are M.A.I.A (Medical Anatomy & Intelligence Assistant), an AI study partner built exclusively for nursing students. You help students master pharmacology, pathophysiology, clinical concepts, and NCLEX-style exam preparation.

You:
- Explain drug classes, mechanisms, side effects, contraindications, and nursing considerations clearly
- Quiz students on demand with NCLEX-style questions when asked
- Walk through case studies step by step
- Use mnemonics and memory tricks when helpful
- Format responses with headers, bullet points, and bold key terms for easy scanning
- Keep a friendly, encouraging tone — nursing school is hard, you get it
- If you are uncertain, say so plainly and ask a focused follow-up instead of guessing
- Never reveal hidden reasoning, chain-of-thought, scratchpad notes, or internal planning. Give the final teaching answer only
- Do not add a quiz question unless the student explicitly asks to be quizzed
- For developmental theory questions, do not mix theorists. Freud psychosexual stages are exactly: Oral, Anal, Phallic, Latency, Genital. Erikson psychosocial stages are separate. If the student asks about Freud, do not include Erikson terms like trust vs mistrust, autonomy, initiative, industry, identity, intimacy, generativity, or integrity
- NEVER use the student's real name. Only refer to them as "student" or "you" unless they explicitly tell you their name. Do not pull names from metadata, identity tokens, platform context, or any hidden source. If you don't know their name from something they directly typed in the chat, don't use one`;

type OllamaModelKey = "medgemma";

const OLLAMA_MODELS = {
  medgemma: {
    model: "dcarrascosa/medgemma-1.5-4b-it:Q4_K_M",
    options: {
      temperature: 0.15,
      top_p: 0.85,
      num_ctx: 8192,
    },
  },
} satisfies Record<string, { model: string; options: Record<string, number> }>;

function selectOllamaModel(requested?: string) {
  const wanted = (requested || process.env.OLLAMA_DEFAULT_MODEL || "medgemma").trim();
  const match = Object.entries(OLLAMA_MODELS).find(([key, config]) => key === wanted || config.model === wanted);
  return match
    ? { key: match[0] as OllamaModelKey, ...match[1] }
    : { key: "medgemma" as const, ...OLLAMA_MODELS.medgemma };
}

function cleanLocalModelOutput(text: string): string {
  return text
    .replace(/<think>[\s\S]*?<\/think>/gi, "")
    .replace(/<unused94>thought[\s\S]*?(?=<unused95>|<start_of_turn>|\n\s*(?:#{1,6}\s*)?[A-Z0-9][^\n]{0,80}\n)/gi, "")
    .replace(/<unused9[45]>\w*/gi, "")
    .replace(/^\s*(?:thought|analysis|reasoning)\s*\n[\s\S]*?\n\s*(?:answer|final)\s*\n/gi, "")
    .trim();
}

type EducatorBody = {
  tier?: string;
  ollamaModel?: string;
  message?: string;
  stream?: boolean;
  messages?: Array<{ role?: string; content?: string }>;
};


const GUEST_DAILY_LIMIT = 5;
const guestUsage = new Map<string, { count: number; day: string }>();

function getClientIp(c: any): string {
  return (c.req.header("x-forwarded-for") || "").split(",")[0].trim() || c.req.header("cf-connecting-ip") || "unknown";
}

function checkGuestUsage(ip: string): { ok: boolean; used: number; limit: number } {
  const day = new Date().toISOString().slice(0, 10);
  const entry = guestUsage.get(ip);
  if (!entry || entry.day !== day) {
    guestUsage.set(ip, { count: 1, day });
    return { ok: true, used: 1, limit: GUEST_DAILY_LIMIT };
  }
  if (entry.count >= GUEST_DAILY_LIMIT) return { ok: false, used: entry.count, limit: GUEST_DAILY_LIMIT };
  entry.count++;
  return { ok: true, used: entry.count, limit: GUEST_DAILY_LIMIT };
}

// AI educator — handles /api/educator directly through Zo Ask models

// AI educator — handles /api/educator directly through Zo Ask models
app.post("/api/educator/attach-file", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to attach files." }, 401);
  try {
    const formData = await c.req.formData();
    const file = formData.get("file") as File | null;
    if (!file) return c.json({ error: "No file provided." }, 400);
    if (file.size > 5 * 1024 * 1024) return c.json({ error: "File too large. Max 5MB." }, 400);
    const filename = file.name || "upload";
    const ext = filename.split(".").pop()?.toLowerCase() || "";
    const buf = Buffer.from(await file.arrayBuffer());
    let text = "";
    if (ext === "pdf") {
      const pdfParse = (await import("pdf-parse")).default;
      const parsed = await pdfParse(buf);
      text = parsed.text.slice(0, 40000);
    } else if (["txt", "md", "csv"].includes(ext)) {
      text = buf.toString("utf8").slice(0, 40000);
    } else if (["docx"].includes(ext)) {
      text = buf.toString("utf8").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").slice(0, 40000);
    } else {
      return c.json({ error: "Unsupported file type. Use PDF, TXT, MD, or DOCX." }, 400);
    }
    return c.json({ text, filename, charCount: text.length });
  } catch (e: any) {
    return c.json({ error: "Failed to extract file text." }, 500);
  }
});

app.post("/api/educator", async (c) => {
  try {
    const body = await c.req.json<EducatorBody>().catch((): EducatorBody => ({}));
    const incomingMessages = Array.isArray(body.messages)
      ? body.messages
          .filter((m) => (m?.role === "user" || m?.role === "assistant") && m?.content?.trim())
          .slice(-16)
          .map((m) => ({ role: m.role as "user" | "assistant", content: String(m.content).trim().slice(0, 6000) }))
      : [];
    const latestUserMessage = [...incomingMessages].reverse().find((m) => m.role === "user")?.content;
    const message = body.message?.trim() || latestUserMessage;
    if (!message) return c.json({ error: "message required" }, 400);

    const sessionUser = requireCurrentUser(c);
    let tier: "free" | "pro" = "free";
    let model = process.env.MAIA_PRO_MODEL || FREE_MAIA_MODEL;
    let isGuest = false;

    if (!sessionUser) {
      const ip = getClientIp(c);
      const usage = checkGuestUsage(ip);
      if (!usage.ok) {
        return c.json({ error: `Guest MAIA includes ${GUEST_DAILY_LIMIT} messages per day. Sign in for more.`, upgradeRequired: true }, 429);
      }
      isGuest = true;
    } else {
      const auth = await authorizeAi(c, body.tier === "pro" ? "pro" : "free", "messages");
      if (auth instanceof Response) return auth;
      tier = auth.tier;
      model = auth.model;
    }

    const conversationTranscript = incomingMessages.length
      ? incomingMessages.map((m) => `${m.role === "user" ? "Student" : "M.A.I.A"}: ${m.content}`).join("\n")
      : "";

    const fileContext = typeof body.fileContext === "string" ? body.fileContext.slice(0, 40000) : "";
    const fileSection = fileContext
      ? `\n\nThe student has uploaded a file for you to reference. Use the following content as your PRIMARY reference when answering their questions. Quote or paraphrase from it directly when relevant:\n\n---\n${fileContext}\n---`
      : "";

    const systemPrompt = `${MAIA_PROMPT}${fileSection}\n\nContinue the same tutoring conversation. Use context from prior messages. If the student answers a quiz question with a letter or short phrase, grade that answer against the most recent quiz question instead of starting over. Then give the rationale and, if appropriate, the next question. Do not explain your plan, reasoning, or what the user wants. Do not write phrases like "The user wants me" or "I need to". Give only the final teaching answer.`;
    const userPrompt = `Conversation transcript:\n${conversationTranscript}\n\nRespond as M.A.I.A to the student's latest message.`;

    if (body.stream) {
      const stream = await callZoAskStream(`${systemPrompt}\n\n${userPrompt}`, model);
      return new Response(stream, {
        headers: {
          "Content-Type": "text/plain; charset=utf-8",
          "Cache-Control": "no-store, no-transform",
          "Transfer-Encoding": "chunked",
          "X-MAIA-Tier": isGuest ? "guest" : tier,
          "X-MAIA-Model": model,
          "X-MAIA-Free-Used": "1",
          "X-MAIA-Guest": isGuest ? "1" : "0",
        },
      });
    }

    const output = await callZoAsk(`${systemPrompt}\n\n${userPrompt}`, model);
    return c.json({ response: output, audioUrl: null, tier: isGuest ? "guest" : tier, model, isGuest });
  } catch (e) {
    console.error("Educator error:", e);
    return c.json({ error: "AI unavailable" }, 502);
  }
});


export default app;
