import { Hono } from "hono";
import { ensureDir, readJsonFile, safeId, writeJsonFile } from "../lib/storage";
import { getPlanTier, getStoredUser, requireCurrentUser } from "../lib/auth-helpers";
import { DATA_ROOT } from "../lib/constants";
// <auto-generated from server.ts> — route module for files

const app = new Hono();

// ── File Library ─────────────────────────────────────────────────────────────
function userFilesDir(userId: string) { return path.join(DATA_ROOT, "files", safeId(userId)); }
function userFilesIndex(userId: string) { return path.join(userFilesDir(userId), "index.json"); }
function fileDir(userId: string, fileId: string) { return path.join(userFilesDir(userId), fileId); }

async function extractTextFromBuffer(buffer: Buffer, mimeType: string, filename: string): Promise<string> {
  if (mimeType === "text/plain" || filename.endsWith(".txt")) {
    return buffer.toString("utf8").slice(0, 200000);
  }
  if (mimeType === "application/pdf" || filename.endsWith(".pdf")) {
    const maxLen = 200000;
    try {
      const pdfParse = (await import("pdf-parse")).default;
      const result = await pdfParse(buffer);
      const text = (result.text || "").trim();
      if (text.length > 50) return text.slice(0, maxLen);
    } catch { /* fall through to pdftotext */ }

    // pdftotext fallback
    try {
      const tmpDir = path.join(DATA_ROOT, "tmp");
      await ensureDir(tmpDir);
      const tmpFile = path.join(tmpDir, `extract_${Date.now()}_${Math.random().toString(36).slice(2)}.pdf`);
      await writeFile(tmpFile, buffer);
      const execFileP = promisify(execFile);
      const { stdout } = await execFileP("pdftotext", ["-layout", tmpFile, "-"], { timeout: 30000, maxBuffer: 5 * 1024 * 1024 });
      try { await unlink(tmpFile); } catch {}
      const text = (stdout || "").trim();
      if (text.length > 0) return text.slice(0, maxLen);
    } catch (e: any) {
      console.error(`pdftotext extraction failed for ${filename}:`, e.message || e);
    }
    return "";
  }
  return buffer.toString("utf8").slice(0, 200000);
}


app.post("/api/files/upload", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to upload files." }, 401);
  try {
    const formData = await c.req.formData();
    const file = formData.get("file") as File | null;
    if (!file) return c.json({ error: "No file provided." }, 400);
    if (file.size > 20 * 1024 * 1024) return c.json({ error: "File too large. Max 20MB." }, 413);
    const allowed = ["application/pdf", "text/plain", "text/csv", "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
    if (!allowed.includes(file.type) && !file.name.match(/\.(pdf|txt|csv|docx?|md)$/i)) {
      return c.json({ error: "Unsupported file type. Allowed: PDF, TXT, CSV, DOCX, MD." }, 415);
    }
    const account = await getStoredUser(user);
    const tier = getPlanTier(account);
    const index = await readJsonFile<any[]>(userFilesIndex(user.id), []);
    if (tier === "free" && index.length >= FREE_FILE_LIMIT) {
      return c.json({ error: `Free plan includes ${FREE_FILE_LIMIT} files. Upgrade to Pro Plus for 1GB storage.`, upgradeRequired: true }, 402);
    }
    if (tier === "pro") {
      return c.json({ error: "File Library requires Pro Plus or Max plan.", upgradeRequired: true }, 402);
    }
    if (tier === "pro_plus") {
      const totalBytes = index.reduce((sum: number, f: any) => sum + (f.size || 0), 0);
      if (totalBytes + file.size > PRO_PLUS_FILE_LIMIT_BYTES) {
        return c.json({ error: "Storage limit reached (1GB). Upgrade to Max for 5GB.", upgradeRequired: true }, 402);
      }
    }
    if (tier === "max") {
      const totalBytes = index.reduce((sum: number, f: any) => sum + (f.size || 0), 0);
      if (totalBytes + file.size > MAX_FILE_LIMIT_BYTES) {
        return c.json({ error: "Storage limit reached (5GB). Please delete some files.", upgradeRequired: false }, 402);
      }
    }
    const fileId = `file_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`;
    const dir = fileDir(user.id, fileId);
    await ensureDir(dir);
    const buffer = Buffer.from(await file.arrayBuffer());
    await writeFile(path.join(dir, "original"), buffer);
    const extractedText = await extractTextFromBuffer(buffer, file.type, file.name);
    await writeFile(path.join(dir, "text.txt"), extractedText, "utf8");
    const meta = { id: fileId, name: file.name, size: file.size, type: file.type, uploadedAt: new Date().toISOString(), textLength: extractedText.length };
    await writeFile(path.join(dir, "meta.json"), JSON.stringify(meta));
    index.push(meta);
    await writeJsonFile(userFilesIndex(user.id), index);
    return c.json({ file: meta });
  } catch (e: any) {
    console.error("File upload error:", e);
    return c.json({ error: e.message || "Upload failed." }, 500);
  }
});

app.get("/api/files", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to view files." }, 401);
  const index = await readJsonFile<any[]>(userFilesIndex(user.id), []);
  return c.json(index.sort((a, b) => b.uploadedAt.localeCompare(a.uploadedAt)));
});

app.delete("/api/files/:fileId", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Unauthorized." }, 401);
  const fileId = c.req.param("fileId");
  if (!/^file_[a-zA-Z0-9_]+$/.test(fileId)) return c.json({ error: "Invalid file ID." }, 400);
  try {
    const { rm } = await import("node:fs/promises");
    await rm(fileDir(user.id, fileId), { recursive: true, force: true });
    const index = await readJsonFile<any[]>(userFilesIndex(user.id), []);
    await writeJsonFile(userFilesIndex(user.id), index.filter((f) => f.id !== fileId));
    return c.json({ ok: true });
  } catch (e: any) {
    return c.json({ error: "Delete failed." }, 500);
  }
});

app.get("/api/files/:fileId/text", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Unauthorized." }, 401);
  const fileId = c.req.param("fileId");
  try {
    const text = await readFile(path.join(fileDir(user.id, fileId), "text.txt"), "utf8");
    return c.text(text);
  } catch {
    return c.json({ error: "File not found." }, 404);
  }
});
// ─────────────────────────────────────────────────────────────────────────────


export default app;
