import { Hono } from "hono";
import { ensureDir, readJsonFile, writeJsonFile } from "../lib/storage";
import { getPlanTier, getStoredUser, requireCurrentUser } from "../lib/auth-helpers";
import { getZoToken } from "../lib/maia";
import { DATA_ROOT, PRO_MAIA_MODEL, proceduresDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for knowledge-web

const app = new Hono();


app.post("/api/web/generate", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to generate a knowledge web." }, 401);
  const account = await getStoredUser(user);
  const tier = getPlanTier(account);
  if (tier === "free") return c.json({ error: "Knowledge webs require a Pro plan or higher.", upgradeRequired: true }, 402);

  const body = await c.req.json().catch(() => ({})) as { fileIds?: string[]; title?: string };
  if (!body.fileIds?.length) return c.json({ error: "Select at least one file." }, 400);

  await ensureDir(userWebDir(user.id));

  const stub: WebGraph = {
    userId: user.id,
    nodes: {},
    rootNodeIds: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  await writeJsonFile(webPath(user.id), stub);

  (async () => {
    try {
      const texts: string[] = [];
      for (const fid of body.fileIds!) {
        try {
          const t = await readFile(path.join(fileDir(user.id, fid), "text.txt"), "utf8");
          texts.push(t.slice(0, 50000));
        } catch {}
      }
      const combinedText = texts.join("\n\n---\n\n").slice(0, 120000);
      const token = await getZoToken();
      if (!token) throw new Error("No AI token");

      const prompt = buildWebGeneratePrompt(combinedText);
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ input: prompt, model_name: process.env.MAIA_PRO_MODEL || PRO_MAIA_MODEL }),
      });
      const data = await resp.json() as { output?: string };
      const raw = (data.output || "").replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const generated = JSON.parse(raw);

      const nodes: Record<string, WebNode> = {};
      const now = new Date().toISOString();
      for (const [id, node] of Object.entries(generated.nodes || {})) {
        const n = node as any;
        nodes[id] = {
          id,
          title: n.title || id,
          content: n.content || "",
          category: WEB_NODE_CATEGORIES.includes(n.category) ? n.category : "fundamentals",
          prerequisites: n.prerequisites || [],
          related: n.related || [],
          quiz: (n.quiz || []).map((q: any) => ({
            id: q.id || `${id}_q${Math.random().toString(36).slice(2, 6)}`,
            question: q.question || "",
            options: q.options || [],
            correctOption: q.correctOption || "",
            explanation: q.explanation || "",
          })),
          xpValue: n.xpValue || 25,
          source: "from-note",
          depth: n.depth ?? 0,
          createdAt: now,
        };
      }

      const updated: WebGraph = {
        ...stub,
        nodes,
        rootNodeIds: generated.rootNodeIds || Object.entries(nodes).filter(([_, n]) => n.depth === 0).map(([id]) => id),
        updatedAt: now,
      };
      layoutWebGraph(updated);
      await writeJsonFile(webPath(user.id), updated);

      // Initialize progress
      const progress = await getOrCreateWebProgress(user.id);
      for (const nodeId of Object.keys(nodes)) {
        if (!progress.nodes[nodeId]) {
          progress.nodes[nodeId] = {
            status: "available",
            sm2: { ease: 2.5, interval: 1, repetitions: 0, nextReview: now },
            answeredCorrect: 0,
            totalAnswered: 0,
            xpEarned: 0,
          };
        }
      }
      progress.updatedAt = now;
      await writeJsonFile(webProgressPath(user.id), progress);
    } catch (e) {
      console.error("Web generation error:", e);
      await writeJsonFile(webPath(user.id), { ...stub, updatedAt: new Date().toISOString() });
    }
  })();

  return c.json({ ok: true, message: "Generating knowledge web…" });
});

app.post("/api/web/generate-from-topic", async (c) => {
  const adminBypass = isAdminBypass(c);
  if (!adminBypass) {
    const realUser = requireCurrentUser(c);
    if (!realUser) return c.json({ error: "Sign in to generate a knowledge web." }, 401);
    const account = await getStoredUser(realUser);
    const tier = getPlanTier(account);
    if (tier === "free") return c.json({ error: "Knowledge webs require a Pro plan or higher.", upgradeRequired: true }, 402);
  }
  const effectiveUserId = adminBypass ? "demo_admin" : requireCurrentUser(c)!.id;

  const body = await c.req.json().catch(() => ({})) as { topic?: string };
  if (!body.topic?.trim()) return c.json({ error: "Provide a topic." }, 400);

  await ensureDir(userWebDir(effectiveUserId));

  const stub: WebGraph = {
    userId: effectiveUserId, nodes: {}, rootNodeIds: [],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  };
  await writeJsonFile(webPath(effectiveUserId), stub);

  (async () => {
    try {
      const token = await getZoToken();
      if (!token) throw new Error("No AI token");

      const prompt = buildWebFromTopicPrompt(body.topic!);
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ input: prompt, model_name: process.env.MAIA_PRO_MODEL || PRO_MAIA_MODEL }),
      });
      const data = await resp.json() as { output?: string };
      const raw = (data.output || "").replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const generated = JSON.parse(raw);

      const nodes: Record<string, WebNode> = {};
      const now = new Date().toISOString();
      for (const [id, node] of Object.entries(generated.nodes || {})) {
        const n = node as any;
        nodes[id] = {
          id, title: n.title || id, content: n.content || "",
          category: WEB_NODE_CATEGORIES.includes(n.category) ? n.category : "fundamentals",
          prerequisites: n.prerequisites || [], related: n.related || [],
          quiz: (n.quiz || []).map((q: any) => ({
            id: q.id || `${id}_q${Math.random().toString(36).slice(2, 6)}`,
            question: q.question || "", options: q.options || [],
            correctOption: q.correctOption || "", explanation: q.explanation || "",
          })),
          xpValue: n.xpValue || 25, source: "ai-generated", depth: n.depth ?? 0, createdAt: now,
        };
      }

      const updated: WebGraph = {
        ...stub, nodes,
        rootNodeIds: generated.rootNodeIds || Object.entries(nodes).filter(([_, n]) => n.depth === 0).map(([id]) => id),
        updatedAt: now,
      };
      layoutWebGraph(updated);
      await writeJsonFile(webPath(effectiveUserId), updated);

      const progress = await getOrCreateWebProgress(effectiveUserId);
      for (const nodeId of Object.keys(nodes)) {
        if (!progress.nodes[nodeId]) {
          progress.nodes[nodeId] = {
            status: "available",
            sm2: { ease: 2.5, interval: 1, repetitions: 0, nextReview: now },
            answeredCorrect: 0, totalAnswered: 0, xpEarned: 0,
          };
        }
      }
      progress.updatedAt = now;
      await writeJsonFile(webProgressPath(effectiveUserId), progress);
    } catch (e) {
      console.error("Web topic generation error:", e);
      await writeJsonFile(webPath(effectiveUserId), { ...stub, updatedAt: new Date().toISOString() });
    }
  })();

  return c.json({ ok: true, message: "Generating knowledge web from topic…" });
});

app.post("/api/web/add-files", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const account = await getStoredUser(user);
  const tier = getPlanTier(account);
  if (tier === "free") return c.json({ error: "Knowledge webs require a Pro plan or higher.", upgradeRequired: true }, 402);

  const body = await c.req.json().catch(() => ({})) as { fileIds?: string[] };
  if (!body.fileIds?.length) return c.json({ error: "Select at least one file." }, 400);

  const existing = await readJsonFile<WebGraph>(webPath(user.id), null as any);
  if (!existing || !Object.keys(existing.nodes).length) {
    return c.json({ error: "No existing knowledge web found. Generate one first.", upgradeRequired: false }, 400);
  }

  await writeJsonFile(webPath(user.id), { ...existing, updatedAt: new Date().toISOString() });

  (async () => {
    try {
      const texts: string[] = [];
      for (const fid of body.fileIds!) {
        try {
          const t = await readFile(path.join(fileDir(user.id, fid), "text.txt"), "utf8");
          texts.push(t.slice(0, 50000));
        } catch {}
      }
      const combinedText = texts.join("\n\n---\n\n").slice(0, 120000);
      const token = await getZoToken();
      if (!token) throw new Error("No AI token");

      const prompt = buildWebGeneratePrompt(combinedText, existing);
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ input: prompt, model_name: process.env.MAIA_PRO_MODEL || PRO_MAIA_MODEL }),
      });
      const data = await resp.json() as { output?: string };
      const raw = (data.output || "").replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const generated = JSON.parse(raw);

      const now = new Date().toISOString();
      const progress = await getOrCreateWebProgress(user.id);
      let newNodeCount = 0;

      for (const [id, node] of Object.entries(generated.nodes || {})) {
        const n = node as any;
        if (existing.nodes[id]) {
          // Enrich existing node
          const existingNode = existing.nodes[id];
          if (n.content && n.content !== existingNode.content) {
            existingNode.content = existingNode.content + "\n\n---\n\n### Additional Material\n\n" + n.content;
          }
          if (n.quiz?.length) {
            existingNode.quiz.push(...n.quiz.filter((q: any) =>
              !existingNode.quiz.some(eq => eq.question === q.question)
            ).map((q: any) => ({
              id: q.id || `${id}_q${Math.random().toString(36).slice(2, 6)}`,
              question: q.question || "",
              options: q.options || [],
              correctOption: q.correctOption || "",
              explanation: q.explanation || "",
            })));
          }
          if (n.related?.length) {
            existingNode.related = [...new Set([...existingNode.related, ...n.related])];
          }
        } else {
          existing.nodes[id] = {
            id,
            title: n.title || id,
            content: n.content || "",
            category: WEB_NODE_CATEGORIES.includes(n.category) ? n.category : "fundamentals",
            prerequisites: n.prerequisites || [],
            related: n.related || [],
            quiz: (n.quiz || []).map((q: any) => ({
              id: q.id || `${id}_q${Math.random().toString(36).slice(2, 6)}`,
              question: q.question || "",
              options: q.options || [],
              correctOption: q.correctOption || "",
              explanation: q.explanation || "",
            })),
            xpValue: n.xpValue || 25,
            source: "from-note",
            depth: n.depth ?? 0,
            createdAt: now,
            position: undefined,
          };
          progress.nodes[id] = {
            status: "available",
            sm2: { ease: 2.5, interval: 1, repetitions: 0, nextReview: now },
            answeredCorrect: 0,
            totalAnswered: 0,
            xpEarned: 0,
          };
          newNodeCount++;
        }
      }

      if (generated.rootNodeIds?.length) {
        existing.rootNodeIds = [...new Set([...existing.rootNodeIds, ...generated.rootNodeIds])];
      }

      existing.updatedAt = now;
      layoutWebGraph(existing);
      await writeJsonFile(webPath(user.id), existing);
      progress.updatedAt = now;
      await writeJsonFile(webProgressPath(user.id), progress);
    } catch (e) {
      console.error("Web add-files error:", e);
    }
  })();

  return c.json({ ok: true, message: "Adding new content to knowledge web…" });
});

app.get("/api/web", async (c) => {
  const adminBypass = isAdminBypass(c);
  const user = adminBypass ? null : requireCurrentUser(c);
  if (!user && !adminBypass) return c.json({ error: "Sign in." }, 401);
  
  let userId: string;
  if (adminBypass) {
    // Admin mode: scan webs dir for any user's web
    const websDir = userWebDir("");
    try {
      const entries = await readdir(path.join(DATA_ROOT, "webs"));
      const webFiles = entries.filter(f => f.endsWith(".json") && !f.includes("-progress"));
      if (!webFiles.length) return c.json({ exists: false, nodes: {}, rootNodeIds: [] });
      // Look up the graph to get the userId from it
      const graph = await readJsonFile<WebGraph>(path.join(websDir, webFiles[0]), null as any);
      if (!graph) return c.json({ exists: false, nodes: {}, rootNodeIds: [] });
      userId = graph.userId;
    } catch {
      return c.json({ exists: false, nodes: {}, rootNodeIds: [] });
    }
  } else {
    userId = user!.id;
  }
  
  const graph = await readJsonFile<WebGraph>(webPath(userId), null as any);
  if (!graph || !Object.keys(graph.nodes).length) {
    return c.json({ exists: false, nodes: {}, rootNodeIds: [] });
  }
  const progress = await getOrCreateWebProgress(userId);

  // Compute live status for each node
  const nodesWithStatus: Record<string, any> = {};
  for (const [id, node] of Object.entries(graph.nodes)) {
    const status = computeNodeStatus(id, node, graph.nodes, progress);
    const np = progress.nodes[id];
    nodesWithStatus[id] = {
      ...node,
      status,
      progress: np ? {
        answeredCorrect: np.answeredCorrect,
        totalAnswered: np.totalAnswered,
        sm2: np.sm2,
      } : null,
    };
  }

  return c.json({
    exists: true,
    nodes: nodesWithStatus,
    rootNodeIds: graph.rootNodeIds,
    updatedAt: graph.updatedAt,
  });
});

app.get("/api/web/nodes/:nodeId", async (c) => {
  const adminBypass = isAdminBypass(c);
  const user = adminBypass ? null : requireCurrentUser(c);
  if (!user && !adminBypass) return c.json({ error: "Sign in." }, 401);
  const userId = adminBypass ? await resolveFirstWebUserId() : user!.id;
  if (!userId) return c.json({ error: "No knowledge web found." }, 404);
  const graph = await readJsonFile<WebGraph>(webPath(userId), null as any);
  if (!graph) return c.json({ error: "No knowledge web found." }, 404);
  const nodeId = c.req.param("nodeId");
  const node = graph.nodes[nodeId];
  if (!node) return c.json({ error: "Node not found." }, 404);
  const progress = await getOrCreateWebProgress(userId);
  const status = computeNodeStatus(nodeId, node, graph.nodes, progress);
  const np = progress.nodes[nodeId];
  return c.json({
    ...node,
    status,
    progress: np ? {
      answeredCorrect: np.answeredCorrect,
      totalAnswered: np.totalAnswered,
      sm2: np.sm2,
    } : null,
    canAccess: status !== "locked",
  });
});

app.post("/api/web/nodes/:nodeId/expand", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const account = await getStoredUser(user);
  if (getPlanTier(account) === "free") return c.json({ error: "Requires a Pro plan or higher.", upgradeRequired: true }, 402);

  const nodeId = c.req.param("nodeId");
  const graph = await readJsonFile<WebGraph>(webPath(user.id), null as any);
  if (!graph) return c.json({ error: "No knowledge web found." }, 404);
  const node = graph.nodes[nodeId];
  if (!node) return c.json({ error: "Node not found." }, 404);

  await writeJsonFile(webPath(user.id), { ...graph, updatedAt: new Date().toISOString() });

  (async () => {
    try {
      const token = await getZoToken();
      if (!token) throw new Error("No AI token");

      const prompt = buildWebExpandPrompt(node, graph);
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ input: prompt, model_name: process.env.MAIA_PRO_MODEL || PRO_MAIA_MODEL }),
      });
      const data = await resp.json() as { output?: string };
      const raw = (data.output || "").replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const generated = JSON.parse(raw);

      const now = new Date().toISOString();
      const progress = await getOrCreateWebProgress(user.id);
      const newIds: string[] = [];

      for (const [id, newNode] of Object.entries(generated.nodes || {})) {
        const n = newNode as any;
        if (graph.nodes[id]) continue; // skip duplicates
        const prefix = `n_${nodeId.slice(2)}`;
        const freshId = `${prefix}_exp${newIds.length + 1}_${now.slice(11, 19).replace(/:/g, "")}`;
        graph.nodes[freshId] = {
          id: freshId,
          title: n.title || `Expansion on ${node.title}`,
          content: n.content || "",
          category: WEB_NODE_CATEGORIES.includes(n.category) ? n.category : node.category,
          prerequisites: [nodeId, ...(n.prerequisites || [])],
          related: n.related || [nodeId],
          quiz: (n.quiz || []).map((q: any) => ({
            id: q.id || `${freshId}_q${Math.random().toString(36).slice(2, 6)}`,
            question: q.question || "",
            options: q.options || [],
            correctOption: q.correctOption || "",
            explanation: q.explanation || "",
          })),
          xpValue: n.xpValue || 30,
          source: "ai-expanded",
          depth: node.depth + 1,
          createdAt: now,
        };
        progress.nodes[freshId] = {
          status: "locked",
          sm2: { ease: 2.5, interval: 1, repetitions: 0, nextReview: now },
          answeredCorrect: 0,
          totalAnswered: 0,
          xpEarned: 0,
        };
        newIds.push(freshId);
      }

      graph.updatedAt = now;
      layoutWebGraph(graph);
      await writeJsonFile(webPath(user.id), graph);
      progress.updatedAt = now;
      await writeJsonFile(webProgressPath(user.id), progress);
    } catch (e) {
      console.error("Web expand error:", e);
    }
  })();

  return c.json({ ok: true, message: `Expanding from "${node.title}"…` });
});

app.post("/api/web/nodes/:nodeId/enrich", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const account = await getStoredUser(user);
  if (getPlanTier(account) === "free") return c.json({ error: "Requires a Pro plan or higher.", upgradeRequired: true }, 402);

  const nodeId = c.req.param("nodeId");
  const body = await c.req.json().catch(() => ({})) as { fileIds?: string[]; customContent?: string };
  if (!body.fileIds?.length && !body.customContent) return c.json({ error: "Provide fileIds or custom content." }, 400);

  const graph = await readJsonFile<WebGraph>(webPath(user.id), null as any);
  if (!graph) return c.json({ error: "No knowledge web found." }, 404);
  const node = graph.nodes[nodeId];
  if (!node) return c.json({ error: "Node not found." }, 404);

  let newContent = body.customContent || "";
  if (body.fileIds?.length) {
    const texts: string[] = [];
    for (const fid of body.fileIds!) {
      try {
        const t = await readFile(path.join(fileDir(user.id, fid), "text.txt"), "utf8");
        texts.push(t.slice(0, 50000));
      } catch {}
    }
    newContent = texts.join("\n\n---\n\n").slice(0, 120000);
  }

  (async () => {
    try {
      const token = await getZoToken();
      if (!token) throw new Error("No AI token");

      const prompt = buildEnrichPrompt(node, newContent);
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ input: prompt, model_name: process.env.MAIA_PRO_MODEL || PRO_MAIA_MODEL }),
      });
      const data = await resp.json() as { output?: string };
      const raw = (data.output || "").replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const enriched = JSON.parse(raw);

      if (enriched.content) node.content = enriched.content;
      if (enriched.addedQuiz?.length) {
        node.quiz.push(...enriched.addedQuiz.map((q: any) => ({
          id: q.id || `${nodeId}_q${Math.random().toString(36).slice(2, 6)}`,
          question: q.question || "",
          options: q.options || [],
          correctOption: q.correctOption || "",
          explanation: q.explanation || "",
        })));
      }
      if (enriched.addedPrerequisites?.length) {
        node.prerequisites = [...new Set([...node.prerequisites, ...enriched.addedPrerequisites])];
      }
      if (enriched.addedRelated?.length) {
        node.related = [...new Set([...node.related, ...enriched.addedRelated])];
      }

      graph.updatedAt = new Date().toISOString();
      await writeJsonFile(webPath(user.id), graph);
    } catch (e) {
      console.error("Web enrich error:", e);
    }
  })();

  return c.json({ ok: true, message: `Enriching "${node.title}"…` });
});

app.post("/api/web/nodes/:nodeId/quiz", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);

  const nodeId = c.req.param("nodeId");
  const body = await c.req.json().catch(() => ({})) as { answers: Record<string, string> };
  if (!body.answers || !Object.keys(body.answers).length) {
    return c.json({ error: "Provide answers to quiz questions." }, 400);
  }

  const graph = await readJsonFile<WebGraph>(webPath(user.id), null as any);
  if (!graph) return c.json({ error: "No knowledge web found." }, 404);
  const node = graph.nodes[nodeId];
  if (!node) return c.json({ error: "Node not found." }, 404);

  const progress = await getOrCreateWebProgress(user.id);
  let np = progress.nodes[nodeId];
  if (!np) {
    np = {
      status: "locked",
      sm2: { ease: 2.5, interval: 1, repetitions: 0, nextReview: new Date().toISOString() },
      answeredCorrect: 0,
      totalAnswered: 0,
      xpEarned: 0,
    };
  }

  // Grade answers
  let correct = 0;
  let total = 0;
  const results: Record<string, { correct: boolean; expected: string }> = {};

  for (const [qId, answer] of Object.entries(body.answers)) {
    const question = node.quiz.find(q => q.id === qId);
    if (!question) continue;
    total++;
    const isCorrect = answer.trim().toLowerCase() === question.correctOption.trim().toLowerCase();
    if (isCorrect) correct++;
    results[qId] = { correct: isCorrect, expected: question.correctOption };
  }

  np.totalAnswered = (np.totalAnswered || 0) + total;
  np.answeredCorrect = (np.answeredCorrect || 0) + correct;

  const pct = total > 0 ? correct / total : 0;

  // SM-2 update
  const quality = pct >= 0.9 ? 5 : pct >= 0.75 ? 4 : pct >= 0.5 ? 3 : pct >= 0.3 ? 2 : 1;
  const sm2 = np.sm2 || { ease: 2.5, interval: 1, repetitions: 0, nextReview: new Date().toISOString() };
  if (quality < 3) {
    sm2.interval = 1;
    sm2.repetitions = 0;
  } else {
    sm2.interval = sm2.repetitions === 0 ? 1 : sm2.repetitions === 1 ? 6 : Math.round(sm2.interval * sm2.ease);
    sm2.repetitions += 1;
    sm2.ease = Math.max(1.3, sm2.ease + 0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
  }
  sm2.nextReview = new Date(Date.now() + sm2.interval * 24 * 60 * 60 * 1000).toISOString();
  np.sm2 = sm2;

  // Mastery
  const newlyMastered = pct >= 0.8 && total >= node.quiz.length && np.status !== "mastered";
  if (newlyMastered) {
    np.status = "mastered";
    np.completedAt = new Date().toISOString();
    np.xpEarned = node.xpValue;
    progress.totalXp += node.xpValue;
    await updateUserStats(user.id, node.xpValue);
  } else if (np.status === "locked" || np.status === "available") {
    np.status = "in-progress";
  }

  progress.nodes[nodeId] = np;
  progress.updatedAt = new Date().toISOString();
  await writeJsonFile(webProgressPath(user.id), progress);

  const stats = await getUserStats(user.id);

  return c.json({
    results,
    correct,
    total,
    pct: Math.round(pct * 100),
    mastered: newlyMastered,
    xpEarned: newlyMastered ? node.xpValue : 0,
    sm2: { nextReview: sm2.nextReview, interval: sm2.interval, ease: sm2.ease },
    stats,
    newlyUnlocked: newlyMastered ? Object.values(graph.nodes)
      .filter(n => n.prerequisites.includes(nodeId) && computePrerequisitesMet(n, progress))
      .map(n => ({ id: n.id, title: n.title })) : [],
  });
});

app.get("/api/web/progress", async (c) => {
  const adminBypass = isAdminBypass(c);
  const user = adminBypass ? null : requireCurrentUser(c);
  if (!user && !adminBypass) return c.json({ error: "Sign in." }, 401);
  const userId = adminBypass ? (await resolveFirstWebUserId() || "") : user!.id;
  if (!userId) return c.json({ nodes: {}, totalXp: 0, userId: '' });
  const progress = await getOrCreateWebProgress(userId);
  return c.json(progress);
});

app.get("/api/web/due", async (c) => {
  const adminBypass = isAdminBypass(c);
  const user = adminBypass ? null : requireCurrentUser(c);
  if (!user && !adminBypass) return c.json({ error: "Sign in." }, 401);
  const userId = adminBypass ? (await resolveFirstWebUserId() || "") : user!.id;
  const graph = await readJsonFile<WebGraph>(webPath(userId), null as any);
  if (!graph) return c.json({ due: [], count: 0 });
  const progress = await getOrCreateWebProgress(userId);
  const now = new Date().toISOString();
  const due: Array<{ nodeId: string; title: string; category: string; nextReview: string }> = [];
  for (const [id, node] of Object.entries(graph.nodes)) {
    const np = progress.nodes[id];
    if (np?.status === "mastered" && np.sm2?.nextReview && np.sm2.nextReview <= now) {
      due.push({ nodeId: id, title: node.title, category: node.category, nextReview: np.sm2.nextReview });
    }
  }
  return c.json({ due, count: due.length });
});

// ─────────────────────────────────────────────────────────────────────────────

// Procedures — loaded from per-category JSON files in data/procedures/
const proceduresDir = path.join(DATA_ROOT, "procedures");

async function loadAllProcedures(): Promise<any[]> {
  try {
    const files = (await readdir(proceduresDir)).filter(
      (f) => f.endsWith(".json") && f !== "index.json"
    );
    const all: any[] = [];
    for (const file of files) {
      const data = await readJsonFile<any[]>(path.join(proceduresDir, file), []);
      all.push(...data);
    }
    return all;
  } catch {
    return [];
  }
}


export default app;
