import { Hono } from "hono";
import { ensureDir, readJsonFile, safeId, writeJsonFile } from "../lib/storage";
import { getCurrentUser } from "../lib/auth-helpers";
import { nclexDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for nclex

const app = new Hono();


app.post("/api/nclex/attempts", async (c) => {
  const user = getCurrentUser(c);
  if (!user) return c.json({ error: "Please sign in to track NCLEX progress." }, 401);
  const body = await c.req.json().catch(() => ({}));
  const filePath = path.join(nclexDir, `${safeId(user.id)}.json`);
  const attempts = await readJsonFile<any[]>(filePath, []);
  const attempt = {
    id: `attempt_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`,
    topic: String(body.topic || "NCLEX practice").slice(0, 120),
    type: body.type === "sata" ? "sata" : "mcq",
    correct: !!body.correct,
    selected: Array.isArray(body.selected) ? body.selected.map(String).slice(0, 8) : [],
    correctAnswers: Array.isArray(body.correctAnswers) ? body.correctAnswers.map(String).slice(0, 8) : [],
    createdAt: new Date().toISOString(),
  };
  attempts.push(attempt);
  await writeJsonFile(filePath, attempts.slice(-500));
  const total = attempts.length;
  const right = attempts.filter((a) => a.correct).length;
  const byTopic: Record<string, { total: number; right: number }> = {};
  for (const item of attempts) {
    const key = String(item.topic || "Other");
    byTopic[key] ||= { total: 0, right: 0 };
    byTopic[key].total++;
    if (item.correct) byTopic[key].right++;
  }
  return c.json({ ok: true, attempt, stats: { total, right, wrong: total - right, percent: total ? Math.round((right / total) * 100) : 0, byTopic } });
});

app.get("/api/nclex/attempts", async (c) => {
  const user = getCurrentUser(c);
  if (!user) return c.json({ attempts: [], stats: { total: 0, right: 0, wrong: 0, percent: 0, byTopic: {} } });
  const attempts = await readJsonFile<any[]>(path.join(nclexDir, `${safeId(user.id)}.json`), []);
  const total = attempts.length;
  const right = attempts.filter((a) => a.correct).length;
  const byTopic: Record<string, { total: number; right: number }> = {};
  for (const item of attempts) {
    const key = String(item.topic || "Other");
    byTopic[key] ||= { total: 0, right: 0 };
    byTopic[key].total++;
    if (item.correct) byTopic[key].right++;
  }
  return c.json({ attempts: attempts.slice(-50).reverse(), stats: { total, right, wrong: total - right, percent: total ? Math.round((right / total) * 100) : 0, byTopic } });
});


async function listJsonFiles<T>(dir: string): Promise<T[]> {
  await ensureDir(dir);
  const files = (await readdir(dir).catch(() => [])).filter((file) => file.endsWith(".json"));
  const items = await Promise.all(files.map((file) => readJsonFile<T | null>(path.join(dir, file), null)));
  return items.filter(Boolean) as T[];
}

function estimateGeminiCostFromActions(actions: number) {
  const estimatedCostPerAction = 0.015;
  return Math.round(actions * estimatedCostPerAction * 100) / 100;
}


export default app;
