import { Hono } from "hono";
import { ensureDir, readJsonFile, safeId, writeJsonFile } from "../lib/storage";
import { getPlanTier, getStoredUser, isPlatformAdmin, requireCurrentUser } from "../lib/auth-helpers";
import { getZoToken } from "../lib/maia";
import { DATA_ROOT, PRO_MAIA_MODEL } from "../lib/constants";
// <auto-generated from server.ts> — route module for pathways

const app = new Hono();

// ── Pathways ──────────────────────────────────────────────────────────────────
function userPathwaysDir(userId: string) { return path.join(DATA_ROOT, "pathways", safeId(userId)); }
function pathwayPath(userId: string, pathwayId: string) { return path.join(userPathwaysDir(userId), `${safeId(pathwayId)}.json`); }
function userProgressDir(userId: string) { return path.join(DATA_ROOT, "progress", safeId(userId)); }
function progressPath(userId: string, pathwayId: string) { return path.join(userProgressDir(userId), `${safeId(pathwayId)}.json`); }
function statsPath(userId: string) { return path.join(DATA_ROOT, "stats", `${safeId(userId)}.json`); }

interface ContentStep {
  id: string; type: "read" | "image" | "video" | "audio";
  title?: string; content: string; caption?: string; duration?: number;
}
interface QuizStep {
  id: string; type: "mcq" | "flashcard";
  question: string; options?: string[]; correctOption?: string;
  answer: string; explanation?: string; hint?: string;
}
type PathwayStep = ContentStep | QuizStep;
interface PathwayLesson { id: string; title: string; steps: PathwayStep[]; xpReward: number; estimatedMinutes?: number; }
interface PathwayBranch { id: string; title: string; condition: string; targetModuleId: string; }
interface PathwayModule { id: string; title: string; lessons: PathwayLesson[]; branches?: PathwayBranch[]; }
interface Pathway {
  id: string; userId: string; title: string; description: string;
  fileIds: string[]; modules: PathwayModule[];
  status: "generating" | "ready" | "error"; createdAt: string; updatedAt: string;
  errorMessage?: string;
}
interface StepProgress { completed: boolean; correct?: boolean; attempts: number; completedAt?: string; }
interface LessonProgress { completed: boolean; xpEarned: number; steps: Record<string, StepProgress>; completedAt?: string; startedAt?: string; }
interface PathwayProgressData { lessons: Record<string, LessonProgress>; totalXp: number; updatedAt: string; }
interface UserStats { totalXp: number; streak: number; longestStreak: number; lastStudiedDate: string; updatedAt: string; }

async function getUserStats(userId: string): Promise<UserStats> {
  return readJsonFile<UserStats>(statsPath(userId), { totalXp: 0, streak: 0, longestStreak: 0, lastStudiedDate: "", updatedAt: new Date().toISOString() });
}

async function updateUserStats(userId: string, xpDelta: number): Promise<UserStats> {
  await ensureDir(path.join(DATA_ROOT, "stats"));
  const stats = await getUserStats(userId);
  const today = new Date().toISOString().slice(0, 10);
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
  let { streak, longestStreak } = stats;
  if (stats.lastStudiedDate === yesterday) streak += 1;
  else if (stats.lastStudiedDate !== today) streak = 1;
  if (streak > longestStreak) longestStreak = streak;
  const updated: UserStats = { totalXp: stats.totalXp + xpDelta, streak, longestStreak, lastStudiedDate: today, updatedAt: new Date().toISOString() };
  await writeJsonFile(statsPath(userId), updated);
  return updated;
}


app.post("/api/pathways/generate", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to generate pathways." }, 401);
  const account = await getStoredUser(user);
  const tier = getPlanTier(account);
  if (!isPlatformAdmin(user)) {
    const pathwayLimit = getPathwayLimit(tier);
    const existingPathways = await readJsonFile<string[]>(path.join(userPathwaysDir(user.id), "index.json"), []).catch(() => [] as string[]);
    const pathwayFiles = await readdir(userPathwaysDir(user.id)).catch(() => [] as string[]);
    const pathwayCount = pathwayFiles.filter(f => f.endsWith(".json") && f !== "index.json").length;
    if (pathwayCount >= pathwayLimit) {
      return c.json({ error: `Your ${tier.replace("_", " ")} plan allows ${pathwayLimit} pathways. Delete one or upgrade to create more.`, upgradeRequired: tier !== "max" }, 402);
    }
  }
  const body = await c.req.json().catch(() => ({})) as { fileIds?: string[]; title?: string };
  if (!body.fileIds?.length) return c.json({ error: "Select at least one file." }, 400);
  const pathwayId = `pw_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`;
  const stub: Pathway = {
    id: pathwayId, userId: user.id, title: body.title || "My Pathway",
    description: "", fileIds: body.fileIds, modules: [], status: "generating",
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  };
  await ensureDir(userPathwaysDir(user.id));
  await writeJsonFile(pathwayPath(user.id, pathwayId), stub);
  (async () => {
    try {
      const texts: string[] = [];
      for (const fid of body.fileIds!) {
        try { const t = await readFile(path.join(fileDir(user.id, fid), "text.txt"), "utf8"); texts.push(t.slice(0, 50000)); } catch {}
      }
      const combinedText = texts.join("\n\n---\n\n").slice(0, 120000);
      if (!combinedText.trim() || combinedText.trim().length < 50) {
        throw new Error("NO_TEXT: The uploaded file contains little or no extractable text. PPT-to-PDF slides and image-based PDFs cannot be used for pathway generation. Please upload a text-based PDF, DOCX, TXT, or MD file instead.");
      }
      const token = await getZoToken();
      if (!token) throw new Error("No AI token");
      const prompt = `You are a nursing education course designer. Create a Duolingo-style learning pathway from this material — each lesson interleaves rich reading content blocks with quiz questions that test that specific content.

MATERIAL:
${combinedText}

Return ONLY valid JSON (no markdown, no commentary):
{
  "title": "Course title",
  "description": "2-sentence description",
  "modules": [
    {
      "id": "m1",
      "title": "Module title",
      "lessons": [
        {
          "id": "m1l1",
          "title": "Lesson title",
          "xpReward": 20,
          "estimatedMinutes": 5,
          "steps": [
            {
              "id": "m1l1s1",
              "type": "read",
              "title": "Section heading",
              "content": "## Section heading\\n\\nDetailed 2-4 paragraph nursing explanation with key concepts bolded using **markdown**. Include clinical relevance, nursing considerations, and memory aids.",
              "duration": 90
            },
            {
              "id": "m1l1s2",
              "type": "mcq",
              "question": "Question directly testing the content above?",
              "options": ["Correct answer", "Plausible distractor", "Plausible distractor", "Plausible distractor"],
              "correctOption": "Correct answer",
              "answer": "Correct answer",
              "explanation": "Explanation of why the correct answer is right and why the distractors are wrong."
            },
            {
              "id": "m1l1s3",
              "type": "read",
              "title": "Next concept",
              "content": "## Next concept\\n\\nMore content...",
              "duration": 60
            },
            {
              "id": "m1l1s4",
              "type": "mcq",
              "question": "Question testing the second concept?",
              "options": ["A","B","C","D"],
              "correctOption": "A",
              "answer": "A",
              "explanation": "Because..."
            }
          ]
        }
      ]
    }
  ]
}

Rules:
- 3-5 modules, 2-4 lessons per module, 4-8 steps per lesson
- ALWAYS alternate: read → quiz → read → quiz (never two reads or two quizzes in a row unless finishing with an extra quiz)
- Reading content must be substantive nursing education (not a stub) — include clinical pearls, drug info, mechanisms, nursing considerations
- Each MCQ must have exactly 4 options; correctOption must exactly match one of the options
- xpReward: 15-30 per lesson
- All step IDs must be unique across the entire pathway`;
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ input: prompt, model_name: process.env.MAIA_PRO_MODEL || PRO_MAIA_MODEL }),
      });
      const data = await resp.json() as { output?: string };
      const raw = (data.output || "").replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const generated = JSON.parse(raw);
      const updated: Pathway = { ...stub, title: generated.title || stub.title, description: generated.description || "", modules: generated.modules || [], status: "ready", updatedAt: new Date().toISOString() };
      await writeJsonFile(pathwayPath(user.id, pathwayId), updated);
    } catch (e) {
      console.error("Pathway generation error:", e);
      const errMsg = e instanceof Error ? e.message : "Unknown error";
      const userMessage = errMsg.startsWith("NO_TEXT:") ? errMsg.slice(8) : (errMsg.includes("JSON") ? "AI generation failed — the material could not be processed into a pathway. Try a different file with more structured content." : "Pathway generation failed. Please try again or use a different file.");
      const failed = await readJsonFile<Pathway>(pathwayPath(user.id, pathwayId), stub);
      await writeJsonFile(pathwayPath(user.id, pathwayId), { ...failed, status: "error", errorMessage: userMessage, updatedAt: new Date().toISOString() });
    }
  })();
  return c.json({ pathwayId, status: "generating" });
});

app.get("/api/pathways", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const q = (c.req.query("q") || "").toLowerCase();
  const status = c.req.query("status") || "";
  const sort = c.req.query("sort") || "newest";
  await ensureDir(userPathwaysDir(user.id));
  const files = (await readdir(userPathwaysDir(user.id)).catch(() => [])).filter((f) => f.endsWith(".json"));
  let pathways = (await Promise.all(files.map((f) => readJsonFile<Pathway>(path.join(userPathwaysDir(user.id), f), null as any)))).filter(Boolean);
  if (q) pathways = pathways.filter(p => p.title.toLowerCase().includes(q) || p.description.toLowerCase().includes(q));
  if (status) pathways = pathways.filter(p => p.status === status);
  if (sort === "oldest") pathways.sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  else pathways.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return c.json(pathways.map(({ id, title, description, status, createdAt, moduleCount, lessonCount, stepCount, fileIds, errorMessage }: any) => ({ id, title, description, status, createdAt, moduleCount: moduleCount || 0, lessonCount: lessonCount || 0, stepCount: stepCount || 0, fileIds: fileIds || [], errorMessage: errorMessage || null })));
});

app.get("/api/pathways/:id", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const pw = await readJsonFile<Pathway>(pathwayPath(user.id, c.req.param("id")), null as any);
  if (!pw || pw.userId !== user.id) return c.json({ error: "Not found." }, 404);
  return c.json(pw);
});

app.delete("/api/pathways/:id", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Unauthorized." }, 401);
  try { const { unlink } = await import("node:fs/promises"); await unlink(pathwayPath(user.id, c.req.param("id"))); return c.json({ ok: true }); }
  catch { return c.json({ error: "Not found." }, 404); }
});

app.post("/api/pathways/:id/retry", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const pwId = c.req.param("id");
  const pw = await readJsonFile<Pathway>(pathwayPath(user.id, pwId), null as any);
  if (!pw || pw.userId !== user.id) return c.json({ error: "Not found." }, 404);
  if (pw.status !== "error") return c.json({ error: "Only failed pathways can be retried." }, 400);
  if (!pw.fileIds?.length) return c.json({ error: "No files attached to this pathway." }, 400);

  await writeJsonFile(pathwayPath(user.id, pwId), { ...pw, status: "generating", errorMessage: undefined, updatedAt: new Date().toISOString() });

  (async () => {
    try {
      const texts: string[] = [];
      for (const fid of pw.fileIds!) {
        try { const t = await readFile(path.join(fileDir(user.id, fid), "text.txt"), "utf8"); texts.push(t.slice(0, 50000)); } catch {}
      }
      const combinedText = texts.join("\n\n---\n\n").slice(0, 120000);
      const trimmed = combinedText.replace(/\s+/g, " ").trim();
      if (!trimmed || trimmed.length < 100) {
        const errMsg = trimmed ? `File text too short (${trimmed.length} characters). The PDF may be image-only — try uploading a text-based PDF or TXT file instead.` : "No text could be extracted from this file. The PDF may be image-only (scanned slides) — try uploading a text-based PDF or TXT file instead.";
        await writeJsonFile(pathwayPath(user.id, pwId), { ...pw, status: "error", errorMessage: errMsg, updatedAt: new Date().toISOString() });
        return;
      }
      const token = await getZoToken();
      if (!token) throw new Error("No AI token");
      const prompt = `You are a nursing education course designer. Create a Duolingo-style learning pathway from this material — each lesson interleaves rich reading content blocks with quiz questions that test that specific content.

MATERIAL:
${combinedText}

Return ONLY valid JSON (no markdown, no commentary):
{
  "title": "Course title",
  "description": "2-sentence description",
  "modules": [
    {
      "id": "m1",
      "title": "Module title",
      "lessons": [
        {
          "id": "m1l1",
          "title": "Lesson title",
          "xpReward": 20,
          "estimatedMinutes": 5,
          "steps": [
            {
              "id": "m1l1s1",
              "type": "read",
              "title": "Section heading",
              "content": "## Section heading\\n\\nDetailed 2-4 paragraph nursing explanation with key concepts bolded using **markdown**. Include clinical relevance, nursing considerations, and memory aids.",
              "duration": 90
            },
            {
              "id": "m1l1s2",
              "type": "mcq",
              "question": "Question directly testing the content above?",
              "options": ["Correct answer", "Plausible distractor", "Plausible distractor", "Plausible distractor"],
              "correctOption": "Correct answer",
              "answer": "Correct answer",
              "explanation": "Explanation of why the correct answer is right and why the distractors are wrong."
            },
            {
              "id": "m1l1s3",
              "type": "read",
              "title": "Next concept",
              "content": "## Next concept\\n\\nMore content...",
              "duration": 60
            },
            {
              "id": "m1l1s4",
              "type": "mcq",
              "question": "Question testing the second concept?",
              "options": ["A","B","C","D"],
              "correctOption": "A",
              "answer": "A",
              "explanation": "Because..."
            }
          ]
        }
      ]
    }
  ]
}

Rules:
- 3-5 modules, 2-4 lessons per module, 4-8 steps per lesson
- ALWAYS alternate: read → quiz → read → quiz (never two reads or two quizzes in a row unless finishing with an extra quiz)
- Reading content must be substantive nursing education (not a stub) — include clinical pearls, drug info, mechanisms, nursing considerations
- Each MCQ must have exactly 4 options; correctOption must exactly match one of the options
- xpReward: 15-30 per lesson
- All step IDs must be unique across the entire pathway`;
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ input: prompt, model_name: process.env.MAIA_PRO_MODEL || PRO_MAIA_MODEL }),
      });
      const data = await resp.json() as { output?: string };
      const raw = (data.output || "").replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const generated = JSON.parse(raw);
      const updated: Pathway = { ...pw, title: generated.title || pw.title, description: generated.description || "", modules: generated.modules || [], status: "ready", errorMessage: undefined, updatedAt: new Date().toISOString() };
      await writeJsonFile(pathwayPath(user.id, pwId), updated);
    } catch (e) {
      console.error("Pathway retry error:", e);
      const errMsg = e instanceof Error ? e.message : "Unknown error";
      const userMessage = errMsg.startsWith("NO_TEXT:") ? errMsg.slice(8) : (errMsg.includes("JSON") ? "AI response couldn't be parsed. The file content may be too short or unstructured for pathway generation." : "Generation failed. The file may be image-only or have insufficient text. Try a different file format.");
      await writeJsonFile(pathwayPath(user.id, pwId), { ...pw, status: "error", errorMessage: userMessage, updatedAt: new Date().toISOString() });
    }
  })();

  return c.json({ pathwayId: pwId, status: "generating" });
});

app.get("/api/user/stats", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  return c.json(await getUserStats(user.id));
});

app.get("/api/pathways/:id/progress", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const pw = await readJsonFile<Pathway>(pathwayPath(user.id, c.req.param("id")), null as any);
  if (!pw || pw.userId !== user.id) return c.json({ error: "Not found." }, 404);
  await ensureDir(userProgressDir(user.id));
  const progress = await readJsonFile<PathwayProgressData>(progressPath(user.id, pw.id), { lessons: {}, totalXp: 0, updatedAt: new Date().toISOString() });
  return c.json(progress);
});

app.post("/api/pathways/:id/progress/step", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const { lessonId, stepId, result, attempts } = await c.req.json().catch(() => ({})) as { lessonId?: string; stepId?: string; result?: "viewed" | "correct" | "incorrect"; attempts?: number };
  if (!lessonId || !stepId || !result) return c.json({ error: "Missing fields." }, 400);
  const pw = await readJsonFile<Pathway>(pathwayPath(user.id, c.req.param("id")), null as any);
  if (!pw || pw.userId !== user.id) return c.json({ error: "Not found." }, 404);
  await ensureDir(userProgressDir(user.id));
  const progress = await readJsonFile<PathwayProgressData>(progressPath(user.id, pw.id), { lessons: {}, totalXp: 0, updatedAt: new Date().toISOString() });
  if (!progress.lessons[lessonId]) progress.lessons[lessonId] = { completed: false, xpEarned: 0, steps: {}, startedAt: new Date().toISOString() };
  const existing = progress.lessons[lessonId].steps[stepId];
  if (!existing?.completed) {
    progress.lessons[lessonId].steps[stepId] = {
      completed: result === "viewed" || result === "correct",
      correct: result === "correct" ? true : result === "incorrect" ? false : undefined,
      attempts: (attempts ?? 1),
      completedAt: result !== "incorrect" ? new Date().toISOString() : undefined,
    };
  }
  progress.updatedAt = new Date().toISOString();
  await writeJsonFile(progressPath(user.id, pw.id), progress);
  return c.json({ ok: true, lessonProgress: progress.lessons[lessonId] });
});

app.post("/api/pathways/:id/progress/lesson", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const { lessonId } = await c.req.json().catch(() => ({})) as { lessonId?: string };
  if (!lessonId) return c.json({ error: "Missing lessonId." }, 400);
  const pw = await readJsonFile<Pathway>(pathwayPath(user.id, c.req.param("id")), null as any);
  if (!pw || pw.userId !== user.id) return c.json({ error: "Not found." }, 404);
  const lesson = pw.modules.flatMap(m => m.lessons).find(l => l.id === lessonId);
  if (!lesson) return c.json({ error: "Lesson not found." }, 404);
  await ensureDir(userProgressDir(user.id));
  const progress = await readJsonFile<PathwayProgressData>(progressPath(user.id, pw.id), { lessons: {}, totalXp: 0, updatedAt: new Date().toISOString() });
  if (!progress.lessons[lessonId]) progress.lessons[lessonId] = { completed: false, xpEarned: 0, steps: {}, startedAt: new Date().toISOString() };
  if (!progress.lessons[lessonId].completed) {
    const xp = lesson.xpReward ?? 20;
    progress.lessons[lessonId].completed = true;
    progress.lessons[lessonId].xpEarned = xp;
    progress.lessons[lessonId].completedAt = new Date().toISOString();
    progress.totalXp = (progress.totalXp || 0) + xp;
    progress.updatedAt = new Date().toISOString();
    await writeJsonFile(progressPath(user.id, pw.id), progress);
    const stats = await updateUserStats(user.id, xp);
    return c.json({ ok: true, xpEarned: xp, stats });
  }
  progress.updatedAt = new Date().toISOString();
  await writeJsonFile(progressPath(user.id, pw.id), progress);
  const stats = await getUserStats(user.id);
  return c.json({ ok: true, xpEarned: 0, stats });
});

app.post("/api/pathways/:id/fork", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const account = await getStoredUser(user);
  const tier = getPlanTier(account);
  if (tier === "free") return c.json({ error: "Forking pathways requires a Pro plan or higher.", upgradeRequired: true }, 402);
  const src = await readJsonFile<Pathway>(pathwayPath(user.id, c.req.param("id")), null as any);
  if (!src || src.userId !== user.id) return c.json({ error: "Not found." }, 404);
  const newId = `pw_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`;
  const forked: Pathway = {
    ...src,
    id: newId,
    title: `${src.title} (Copy)`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  await ensureDir(userPathwaysDir(user.id));
  await writeJsonFile(pathwayPath(user.id, newId), forked);
  return c.json({ id: newId, title: forked.title });
});

app.post("/api/pathways/manual", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const account = await getStoredUser(user);
  const tier = getPlanTier(account);
  if (!["pro_plus", "max"].includes(tier) && !isPlatformAdmin(user)) return c.json({ error: "Pro Plus plan required to create manual pathways.", upgradeRequired: true }, 402);
  const pathways = await readJsonFile<string[]>(path.join(userPathwaysDir(user.id), "index.json"), []).catch(() => []);
  const limit = getPathwayLimit(tier);
  if (pathways.length >= limit) return c.json({ error: `Your plan allows ${limit} pathways. Delete one or upgrade.`, upgradeRequired: tier !== "max" }, 402);
  const body = await c.req.json().catch(() => ({})) as { title?: string; description?: string; modules?: any[] };
  if (!body.title?.trim()) return c.json({ error: "Title is required." }, 400);
  const now = new Date().toISOString();
  const id = `pw_manual_${Date.now().toString(36)}_${randomBytes(4).toString("hex")}`;
  const pathway = {
    id, userId: user.id,
    title: body.title.trim(),
    description: body.description || "",
    fileIds: [],
    modules: body.modules || [],
    status: "ready",
    createdAt: now, updatedAt: now,
  };
  await ensureDir(userPathwaysDir(user.id));
  await writeJsonFile(pathwayPath(user.id, id), pathway);
  const index = [...pathways, id];
  await writeJsonFile(path.join(userPathwaysDir(user.id), "index.json"), index);
  return c.json({ id, pathway }, 201);
});

app.post("/api/pathways/:id/share", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const account = await getStoredUser(user);
  if (!["pro_plus", "max"].includes(getPlanTier(account)) && !isPlatformAdmin(user)) return c.json({ error: "Pro Plus plan required to share pathways.", upgradeRequired: true }, 402);
  const pw = await readJsonFile<any>(pathwayPath(user.id, c.req.param("id")), null);
  if (!pw || pw.userId !== user.id) return c.json({ error: "Pathway not found." }, 404);
  const token = randomBytes(16).toString("hex");
  const shareDir = path.join(DATA_ROOT, "shared-pathways");
  await ensureDir(shareDir);
  await writeJsonFile(path.join(shareDir, `${token}.json`), { pathwayId: pw.id, userId: user.id, createdAt: new Date().toISOString() });
  pw.shareToken = token;
  await writeJsonFile(pathwayPath(user.id, pw.id), pw);
  return c.json({ token, url: `/pathways/shared/${token}` });
});

app.get("/api/pathways/shared/:token", async (c) => {
  const rawToken = c.req.param("token");
  const token = /^[a-f0-9]{32}$/.test(rawToken) ? rawToken : null;
  if (!token) return c.json({ error: "Invalid share token." }, 400);
  const shareDir = path.join(DATA_ROOT, "shared-pathways");
  const meta = await readJsonFile<{ pathwayId: string; userId: string } | null>(path.join(shareDir, `${token}.json`), null);
  if (!meta) return c.json({ error: "Shared pathway not found or link expired." }, 404);
  const pw = await readJsonFile<any>(pathwayPath(meta.userId, meta.pathwayId), null);
  if (!pw) return c.json({ error: "Pathway not found." }, 404);
  const { userId: _u, ...publicPathway } = pw;
  return c.json({ pathway: publicPathway });
});

app.post("/api/pathways/:id/content", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const account = await getStoredUser(user);
  const tier = getPlanTier(account);
  if (tier === "free") return c.json({ error: "Adding content requires a Pro plan or higher.", upgradeRequired: true }, 402);
  const pw = await readJsonFile<Pathway>(pathwayPath(user.id, c.req.param("id")), null as any);
  if (!pw || pw.userId !== user.id) return c.json({ error: "Not found." }, 404);
  if (pw.status !== "ready") return c.json({ error: "Pathway must be ready before adding content." }, 400);
  const body = await c.req.json().catch(() => ({})) as { fileIds?: string[]; topic?: string };
  if (!body.fileIds?.length && !body.topic) return c.json({ error: "Provide fileIds or a topic to extend." }, 400);
  const updatedPw = { ...pw, status: "generating" as const, updatedAt: new Date().toISOString() };
  await writeJsonFile(pathwayPath(user.id, pw.id), updatedPw);
  (async () => {
    try {
      const texts: string[] = [];
      if (body.fileIds?.length) {
        for (const fid of body.fileIds) {
          try { const t = await readFile(path.join(fileDir(user.id, fid), "text.txt"), "utf8"); texts.push(t.slice(0, 40000)); } catch {}
        }
      }
      const token = await getZoToken();
      if (!token) throw new Error("No AI token");
      const existingSummary = pw.modules.map(m => `Module: ${m.title}`).join("\n");
      const prompt = `You are extending an existing nursing education pathway. The pathway already covers:\n${existingSummary}\n\nAdd ${body.topic ? `new content about: ${body.topic}` : "content from this material"} as 1-2 new modules with lessons. ${texts.length ? `\n\nSOURCE MATERIAL:\n${texts.join("\n\n---\n\n").slice(0, 80000)}` : ""}\n\nReturn ONLY valid JSON for the new modules array to append (same structure as existing modules with id, title, lessons array containing steps of type read/mcq/flashcard). Use unique IDs prefixed with "ext_". No markdown, no commentary.`;
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ input: prompt, model_name: process.env.MAIA_PRO_MODEL || PRO_MAIA_MODEL }),
      });
      const data = await resp.json() as { output?: string };
      const raw = (data.output || "").replace(/```json\s*/g, "").replace(/```\s*/g, "").trim();
      const newModules = JSON.parse(raw) as PathwayModule[];
      const final = await readJsonFile<Pathway>(pathwayPath(user.id, pw.id), pw);
      await writeJsonFile(pathwayPath(user.id, pw.id), {
        ...final,
        modules: [...final.modules, ...newModules],
        fileIds: [...(final.fileIds || []), ...(body.fileIds || [])],
        status: "ready",
        updatedAt: new Date().toISOString(),
      });
    } catch (e) {
      console.error("Content extension failed:", e);
      const failed = await readJsonFile<Pathway>(pathwayPath(user.id, pw.id), pw);
      await writeJsonFile(pathwayPath(user.id, pw.id), { ...failed, status: "ready", updatedAt: new Date().toISOString() });
    }
  })();
  return c.json({ ok: true, message: "Extending pathway in background…" });
});

app.post("/api/pathways/:id/sm2", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  const { lessonId, quality } = await c.req.json().catch(() => ({})) as { lessonId?: string; quality?: number };
  if (!lessonId || quality === undefined) return c.json({ error: "Missing lessonId or quality (0-5)." }, 400);
  const pw = await readJsonFile<Pathway>(pathwayPath(user.id, c.req.param("id")), null as any);
  if (!pw || pw.userId !== user.id) return c.json({ error: "Not found." }, 404);
  await ensureDir(userProgressDir(user.id));
  const progress = await readJsonFile<PathwayProgressData>(progressPath(user.id, pw.id), { lessons: {}, totalXp: 0, updatedAt: new Date().toISOString() });
  const lp = progress.lessons[lessonId] || { completed: false, xpEarned: 0, steps: {} };
  const sm2 = (lp as any).sm2 || { ease: 2.5, interval: 1, repetitions: 0 };
  const q = Math.max(0, Math.min(5, quality));
  if (q < 3) {
    sm2.interval = 1;
    sm2.repetitions = 0;
  } else {
    sm2.interval = sm2.repetitions === 0 ? 1 : sm2.repetitions === 1 ? 6 : Math.round(sm2.interval * sm2.ease);
    sm2.repetitions += 1;
    sm2.ease = Math.max(1.3, sm2.ease + 0.1 - (5 - q) * (0.08 + (5 - q) * 0.02));
  }
  const nextReview = new Date(Date.now() + sm2.interval * 24 * 60 * 60 * 1000).toISOString();
  sm2.nextReview = nextReview;
  (lp as any).sm2 = sm2;
  progress.lessons[lessonId] = lp;
  progress.updatedAt = new Date().toISOString();
  await writeJsonFile(progressPath(user.id, pw.id), progress);
  return c.json({ ok: true, nextReview, interval: sm2.interval, ease: sm2.ease });
});

app.get("/api/pathways/due", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in." }, 401);
  await ensureDir(userPathwaysDir(user.id));
  const files = (await readdir(userPathwaysDir(user.id)).catch(() => [])).filter((f) => f.endsWith(".json"));


export default app;
