import { Hono } from "hono";
import { readJsonFile } from "../lib/storage";
import { requireCurrentUser } from "../lib/auth-helpers";
import { DATA_ROOT, proceduresDir } from "../lib/constants";
// <auto-generated from server.ts> — route module for procedures

const app = new Hono();

// Procedures — loaded from per-category JSON files in data/procedures/
const proceduresDir = path.join(DATA_ROOT, "procedures");

async function loadAllProcedures(): Promise<any[]> {
  try {
    const files = (await readdir(proceduresDir)).filter(
      (f) => f.endsWith(".json") && f !== "index.json"
    );
    const all: any[] = [];
    for (const file of files) {
      const data = await readJsonFile<any[]>(path.join(proceduresDir, file), []);
      all.push(...data);
    }
    return all;
  } catch {
    return [];
  }
}


app.get("/api/procedures", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to access procedures." }, 401);
  const procedures = await loadAllProcedures();
  return c.json(procedures.map(({ id, title, category, icon, summary }) => ({ id, title, category, icon, summary })));
});

app.get("/api/procedures/:id", async (c) => {
  const user = requireCurrentUser(c);
  if (!user) return c.json({ error: "Sign in to access procedures." }, 401);
  const procedures = await loadAllProcedures();
  const proc = procedures.find((p) => p.id === c.req.param("id"));
  if (!proc) return c.json({ error: "Procedure not found." }, 404);
  return c.json(proc);
});


export default app;
